'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.8745
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da wsdl, versione=2.0.50727.3038.
'
Namespace Intema.WSMarca.Richiesta
    
    'CODEGEN: L'elemento di estensione WSDL facoltativo 'PolicyReference' dallo spazio dei nomi 'http://schemas.xmlsoap.org/ws/2004/09/policy' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MarcaTemporaleESBSoap11Binding", [Namespace]:="http://marcaTemporale.basilicata.regione.it/")>  _
    Partial Public Class MarcaTemporaleESB
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RichiestaMarcaTemporaleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RichiestaMarcaTemporaleRfcOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://attributeauth.hosting.int:9444/services/MarcaTemporaleESB.MarcaTemporaleE"& _ 
                "SBHttpsSoap11Endpoint"
        End Sub
        
        '''<remarks/>
        Public Event RichiestaMarcaTemporaleCompleted As RichiestaMarcaTemporaleCompletedEventHandler
        
        '''<remarks/>
        Public Event RichiestaMarcaTemporaleRfcCompleted As RichiestaMarcaTemporaleRfcCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://marcaTemporale.basilicata.regione.it/", ResponseNamespace:="http://marcaTemporale.basilicata.regione.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RichiestaMarcaTemporale(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal algoritmoHash As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal imprintByte() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal applicationID As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> Byte()
            Dim results() As Object = Me.Invoke("RichiestaMarcaTemporale", New Object() {algoritmoHash, imprintByte, applicationID})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Function BeginRichiestaMarcaTemporale(ByVal algoritmoHash As String, ByVal imprintByte() As Byte, ByVal applicationID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RichiestaMarcaTemporale", New Object() {algoritmoHash, imprintByte, applicationID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRichiestaMarcaTemporale(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RichiestaMarcaTemporaleAsync(ByVal algoritmoHash As String, ByVal imprintByte() As Byte, ByVal applicationID As String)
            Me.RichiestaMarcaTemporaleAsync(algoritmoHash, imprintByte, applicationID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RichiestaMarcaTemporaleAsync(ByVal algoritmoHash As String, ByVal imprintByte() As Byte, ByVal applicationID As String, ByVal userState As Object)
            If (Me.RichiestaMarcaTemporaleOperationCompleted Is Nothing) Then
                Me.RichiestaMarcaTemporaleOperationCompleted = AddressOf Me.OnRichiestaMarcaTemporaleOperationCompleted
            End If
            Me.InvokeAsync("RichiestaMarcaTemporale", New Object() {algoritmoHash, imprintByte, applicationID}, Me.RichiestaMarcaTemporaleOperationCompleted, userState)
        End Sub
        
        Private Sub OnRichiestaMarcaTemporaleOperationCompleted(ByVal arg As Object)
            If (Not (Me.RichiestaMarcaTemporaleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RichiestaMarcaTemporaleCompleted(Me, New RichiestaMarcaTemporaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://marcaTemporale.basilicata.regione.it/", ResponseNamespace:="http://marcaTemporale.basilicata.regione.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RichiestaMarcaTemporaleRfc(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal applicationID As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal requestRfc() As Byte) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> Byte()
            Dim results() As Object = Me.Invoke("RichiestaMarcaTemporaleRfc", New Object() {applicationID, requestRfc})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Function BeginRichiestaMarcaTemporaleRfc(ByVal applicationID As String, ByVal requestRfc() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RichiestaMarcaTemporaleRfc", New Object() {applicationID, requestRfc}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRichiestaMarcaTemporaleRfc(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RichiestaMarcaTemporaleRfcAsync(ByVal applicationID As String, ByVal requestRfc() As Byte)
            Me.RichiestaMarcaTemporaleRfcAsync(applicationID, requestRfc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RichiestaMarcaTemporaleRfcAsync(ByVal applicationID As String, ByVal requestRfc() As Byte, ByVal userState As Object)
            If (Me.RichiestaMarcaTemporaleRfcOperationCompleted Is Nothing) Then
                Me.RichiestaMarcaTemporaleRfcOperationCompleted = AddressOf Me.OnRichiestaMarcaTemporaleRfcOperationCompleted
            End If
            Me.InvokeAsync("RichiestaMarcaTemporaleRfc", New Object() {applicationID, requestRfc}, Me.RichiestaMarcaTemporaleRfcOperationCompleted, userState)
        End Sub
        
        Private Sub OnRichiestaMarcaTemporaleRfcOperationCompleted(ByVal arg As Object)
            If (Not (Me.RichiestaMarcaTemporaleRfcCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RichiestaMarcaTemporaleRfcCompleted(Me, New RichiestaMarcaTemporaleRfcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
    Public Delegate Sub RichiestaMarcaTemporaleCompletedEventHandler(ByVal sender As Object, ByVal e As RichiestaMarcaTemporaleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RichiestaMarcaTemporaleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
    Public Delegate Sub RichiestaMarcaTemporaleRfcCompletedEventHandler(ByVal sender As Object, ByVal e As RichiestaMarcaTemporaleRfcCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RichiestaMarcaTemporaleRfcCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
End Namespace
