'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.5485
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da wsdl, versione=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="NOTIFICAATTOFATTURABinding", [Namespace]:="http://xmlns.oracle.com/orawsv/GAT2_WS/NOTIFICAATTOFATTURA")>  _
Partial Public Class NOTIFICAATTOFATTURAService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private NOTIFICAPROVVEDIMENTISICOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://sicmobile.regione.basilicata.it/orawsv/GAT2_WS/NOTIFICAATTOFATTURA"
    End Sub
    
    '''<remarks/>
    Public Event NOTIFICAPROVVEDIMENTISICCompleted As NOTIFICAPROVVEDIMENTISICCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("NOTIFICAPROVVEDIMENTISIC", RequestElementName:="NOTIFICAPROVVEDIMENTISICInput", RequestNamespace:="http://xmlns.oracle.com/orawsv/GAT2_WS/NOTIFICAATTOFATTURA", ResponseElementName:="NOTIFICAPROVVEDIMENTISICOutput", ResponseNamespace:="http://xmlns.oracle.com/orawsv/GAT2_WS/NOTIFICAATTOFATTURA", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function NOTIFICAPROVVEDIMENTISIC(<System.Xml.Serialization.XmlElementAttribute("P_TIPODOCSIC-VARCHAR2-IN")> ByVal P_TIPODOCSICVARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("P_STATONOTIFICA-VARCHAR2-IN")> ByVal P_STATONOTIFICAVARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("P_NUMERODOCSIC-NUMBER-IN")> ByVal P_NUMERODOCSICNUMBERIN As Double, <System.Xml.Serialization.XmlElementAttribute("P_MESSAGGIO-VARCHAR2-OUT")> ByVal P_MESSAGGIOVARCHAR2OUT As NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT, <System.Xml.Serialization.XmlElementAttribute("P_IDFATTURA-NUMBER-IN")> ByVal P_IDFATTURANUMBERIN As Double, <System.Xml.Serialization.XmlElementAttribute("P_IDATTO-VARCHAR2-IN")> ByVal P_IDATTOVARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("P_ESITO-NUMBER-OUT")> ByVal P_ESITONUMBEROUT As NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT, <System.Xml.Serialization.XmlElementAttribute("P_DATADOCSIC-VARCHAR2-IN")> ByVal P_DATADOCSICVARCHAR2IN As String, <System.Xml.Serialization.XmlElementAttribute("P_IMPORTO-NUMBER-IN")> ByVal P_IMPORTONUMBERIN As Double, ByRef P_ESITO As Double) As <System.Xml.Serialization.XmlElementAttribute("P_MESSAGGIO")> String
        Dim results() As Object = Me.Invoke("NOTIFICAPROVVEDIMENTISIC", New Object() {P_TIPODOCSICVARCHAR2IN, P_STATONOTIFICAVARCHAR2IN, P_NUMERODOCSICNUMBERIN, P_MESSAGGIOVARCHAR2OUT, P_IDFATTURANUMBERIN, P_IDATTOVARCHAR2IN, P_ESITONUMBEROUT, P_DATADOCSICVARCHAR2IN, P_IMPORTONUMBERIN})
        P_ESITO = CType(results(1),Double)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BeginNOTIFICAPROVVEDIMENTISIC(ByVal P_TIPODOCSICVARCHAR2IN As String, ByVal P_STATONOTIFICAVARCHAR2IN As String, ByVal P_NUMERODOCSICNUMBERIN As Double, ByVal P_MESSAGGIOVARCHAR2OUT As NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT, ByVal P_IDFATTURANUMBERIN As Double, ByVal P_IDATTOVARCHAR2IN As String, ByVal P_ESITONUMBEROUT As NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT, ByVal P_DATADOCSICVARCHAR2IN As String, ByVal P_IMPORTONUMBERIN As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("NOTIFICAPROVVEDIMENTISIC", New Object() {P_TIPODOCSICVARCHAR2IN, P_STATONOTIFICAVARCHAR2IN, P_NUMERODOCSICNUMBERIN, P_MESSAGGIOVARCHAR2OUT, P_IDFATTURANUMBERIN, P_IDATTOVARCHAR2IN, P_ESITONUMBEROUT, P_DATADOCSICVARCHAR2IN, P_IMPORTONUMBERIN}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndNOTIFICAPROVVEDIMENTISIC(ByVal asyncResult As System.IAsyncResult, ByRef P_ESITO As Double) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        P_ESITO = CType(results(1),Double)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Overloads Sub NOTIFICAPROVVEDIMENTISICAsync(ByVal P_TIPODOCSICVARCHAR2IN As String, ByVal P_STATONOTIFICAVARCHAR2IN As String, ByVal P_NUMERODOCSICNUMBERIN As Double, ByVal P_MESSAGGIOVARCHAR2OUT As NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT, ByVal P_IDFATTURANUMBERIN As Double, ByVal P_IDATTOVARCHAR2IN As String, ByVal P_ESITONUMBEROUT As NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT, ByVal P_DATADOCSICVARCHAR2IN As String, ByVal P_IMPORTONUMBERIN As Double)
        Me.NOTIFICAPROVVEDIMENTISICAsync(P_TIPODOCSICVARCHAR2IN, P_STATONOTIFICAVARCHAR2IN, P_NUMERODOCSICNUMBERIN, P_MESSAGGIOVARCHAR2OUT, P_IDFATTURANUMBERIN, P_IDATTOVARCHAR2IN, P_ESITONUMBEROUT, P_DATADOCSICVARCHAR2IN, P_IMPORTONUMBERIN, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub NOTIFICAPROVVEDIMENTISICAsync(ByVal P_TIPODOCSICVARCHAR2IN As String, ByVal P_STATONOTIFICAVARCHAR2IN As String, ByVal P_NUMERODOCSICNUMBERIN As Double, ByVal P_MESSAGGIOVARCHAR2OUT As NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT, ByVal P_IDFATTURANUMBERIN As Double, ByVal P_IDATTOVARCHAR2IN As String, ByVal P_ESITONUMBEROUT As NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT, ByVal P_DATADOCSICVARCHAR2IN As String, ByVal P_IMPORTONUMBERIN As Double, ByVal userState As Object)
        If (Me.NOTIFICAPROVVEDIMENTISICOperationCompleted Is Nothing) Then
            Me.NOTIFICAPROVVEDIMENTISICOperationCompleted = AddressOf Me.OnNOTIFICAPROVVEDIMENTISICOperationCompleted
        End If
        Me.InvokeAsync("NOTIFICAPROVVEDIMENTISIC", New Object() {P_TIPODOCSICVARCHAR2IN, P_STATONOTIFICAVARCHAR2IN, P_NUMERODOCSICNUMBERIN, P_MESSAGGIOVARCHAR2OUT, P_IDFATTURANUMBERIN, P_IDATTOVARCHAR2IN, P_ESITONUMBEROUT, P_DATADOCSICVARCHAR2IN, P_IMPORTONUMBERIN}, Me.NOTIFICAPROVVEDIMENTISICOperationCompleted, userState)
    End Sub
    
    Private Sub OnNOTIFICAPROVVEDIMENTISICOperationCompleted(ByVal arg As Object)
        If (Not (Me.NOTIFICAPROVVEDIMENTISICCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent NOTIFICAPROVVEDIMENTISICCompleted(Me, New NOTIFICAPROVVEDIMENTISICCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.oracle.com/orawsv/GAT2_WS/NOTIFICAATTOFATTURA")>  _
Partial Public Class NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.oracle.com/orawsv/GAT2_WS/NOTIFICAATTOFATTURA")>  _
Partial Public Class NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub NOTIFICAPROVVEDIMENTISICCompletedEventHandler(ByVal sender As Object, ByVal e As NOTIFICAPROVVEDIMENTISICCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class NOTIFICAPROVVEDIMENTISICCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
    
    '''<remarks/>
    Public ReadOnly Property P_ESITO() As Double
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(1),Double)
        End Get
    End Property
End Class
