'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.1433
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Delibera

    '''<summary>
    '''Controllo Testata.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Testata As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo Albero.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Albero As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo Contenuto.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Contenuto As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo pnlDatiDelibera.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents pnlDatiDelibera As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Controllo txtOggetto.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txtOggetto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo ReqTxtOggetto.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents ReqTxtOggetto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Controllo txt_Dbi_Bilancio1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_Dbi_Bilancio1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_Dbi_UPB1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_Dbi_UPB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_Dbi_Cap1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_Dbi_Cap1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_Dbi_Costo1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_Dbi_Costo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRP_NImpegno1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRP_NImpegno1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRP_UPB1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRP_UPB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRP_Cap1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRP_Cap1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRP_Costo1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRP_Costo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRA_NContabile1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRA_NContabile1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRA_UPB1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRA_UPB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRA_Cap1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRA_Cap1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRA_Esercizio1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRA_Esercizio1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRA_Costo1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRA_Costo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_Costo1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_Costo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_UPB1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_UPB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_Cap1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_Cap1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_Esercizio1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_Esercizio1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_NContabile1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_NContabile1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_NAssunzione1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_NAssunzione1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo txt_DRL_Data1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txt_DRL_Data1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo pnlPubblicazione.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents pnlPubblicazione As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Controllo ddlTipoPubblicazione.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents ddlTipoPubblicazione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo btnRegistra.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents btnRegistra As Global.System.Web.UI.WebControls.Button
End Class
