'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.5485
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Osservazioni

    '''<summary>
    '''Controllo Head1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''Controllo Testata.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Testata As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo Albero.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Albero As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo Contenuto.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Contenuto As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo DirGenerale.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DirGenerale As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo DirRagioneria.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DirRagioneria As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo DirContrAmministrativo.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DirContrAmministrativo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo DirProponente.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DirProponente As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo DirSegretarioLegittimita.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DirSegretarioLegittimita As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo VerificaRuolo.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents VerificaRuolo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo DirSegretarioDiPresidenza.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DirSegretarioDiPresidenza As Global.System.Web.UI.WebControls.HiddenField
    '''Controllo AbilitaOssUP.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents AbilitaOssUP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controllo TipoAtto.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents TipoAtto As Global.System.Web.UI.WebControls.HiddenField
End Class
