'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.5472
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da wsdl, versione=2.0.50727.3038.
'

Namespace ProvvedimentiFinderWS
'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="ServizioRicercaSoap", [Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class ServizioRicerca
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private RicercaAttiApprovatiOperationCompleted As System.Threading.SendOrPostCallback
    
    Private GetAllegatoOperationCompleted As System.Threading.SendOrPostCallback
    
    Private GetTipologieProvvedimentoOperationCompleted As System.Threading.SendOrPostCallback
    
        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Timeout = System.Threading.Timeout.Infinite
            Me.Url = ConfigurationManager.AppSettings("ProvvedimentiFinderWS")
        End Sub
    
    '''<remarks/>
    Public Event RicercaAttiApprovatiCompleted As RicercaAttiApprovatiCompletedEventHandler
    
    '''<remarks/>
    Public Event GetAllegatoCompleted As GetAllegatoCompletedEventHandler
    
    '''<remarks/>
    Public Event GetTipologieProvvedimentoCompleted As GetTipologieProvvedimentoCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:RicercaAttiApprovati", RequestNamespace:="http://www.intemaweb.com/provvedimentiamministrativi/types", ResponseElementName:="RicercaAttiApprovatiRisposta", ResponseNamespace:="http://www.intemaweb.com/provvedimentiamministrativi/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function RicercaAttiApprovati(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal Richiesta As Messaggio_RichiestaRicerca, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal Autenticazione As Messaggio_AutenticazioneOperatore) As <System.Xml.Serialization.XmlElementAttribute("Risposta", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> Messaggio_Risposta
        Dim results() As Object = Me.Invoke("RicercaAttiApprovati", New Object() {Richiesta, Autenticazione})
        Return CType(results(0),Messaggio_Risposta)
    End Function
    
    '''<remarks/>
    Public Function BeginRicercaAttiApprovati(ByVal Richiesta As Messaggio_RichiestaRicerca, ByVal Autenticazione As Messaggio_AutenticazioneOperatore, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("RicercaAttiApprovati", New Object() {Richiesta, Autenticazione}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndRicercaAttiApprovati(ByVal asyncResult As System.IAsyncResult) As Messaggio_Risposta
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Messaggio_Risposta)
    End Function
    
    '''<remarks/>
    Public Overloads Sub RicercaAttiApprovatiAsync(ByVal Richiesta As Messaggio_RichiestaRicerca, ByVal Autenticazione As Messaggio_AutenticazioneOperatore)
        Me.RicercaAttiApprovatiAsync(Richiesta, Autenticazione, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub RicercaAttiApprovatiAsync(ByVal Richiesta As Messaggio_RichiestaRicerca, ByVal Autenticazione As Messaggio_AutenticazioneOperatore, ByVal userState As Object)
        If (Me.RicercaAttiApprovatiOperationCompleted Is Nothing) Then
            Me.RicercaAttiApprovatiOperationCompleted = AddressOf Me.OnRicercaAttiApprovatiOperationCompleted
        End If
        Me.InvokeAsync("RicercaAttiApprovati", New Object() {Richiesta, Autenticazione}, Me.RicercaAttiApprovatiOperationCompleted, userState)
    End Sub
    
    Private Sub OnRicercaAttiApprovatiOperationCompleted(ByVal arg As Object)
        If (Not (Me.RicercaAttiApprovatiCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent RicercaAttiApprovatiCompleted(Me, New RicercaAttiApprovatiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetAllegato", RequestNamespace:="http://www.intemaweb.com/provvedimentiamministrativi/types", ResponseElementName:="GetAllegatoRisposta", ResponseNamespace:="http://www.intemaweb.com/provvedimentiamministrativi/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GetAllegato(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal Richiesta As Messaggio_RichiestaAllegato, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal Autenticazione As Messaggio_AutenticazioneOperatore) As <System.Xml.Serialization.XmlElementAttribute("Risposta", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> Messaggio_Risposta
        Dim results() As Object = Me.Invoke("GetAllegato", New Object() {Richiesta, Autenticazione})
        Return CType(results(0),Messaggio_Risposta)
    End Function
    
    '''<remarks/>
    Public Function BeginGetAllegato(ByVal Richiesta As Messaggio_RichiestaAllegato, ByVal Autenticazione As Messaggio_AutenticazioneOperatore, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GetAllegato", New Object() {Richiesta, Autenticazione}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndGetAllegato(ByVal asyncResult As System.IAsyncResult) As Messaggio_Risposta
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Messaggio_Risposta)
    End Function
    
    '''<remarks/>
    Public Overloads Sub GetAllegatoAsync(ByVal Richiesta As Messaggio_RichiestaAllegato, ByVal Autenticazione As Messaggio_AutenticazioneOperatore)
        Me.GetAllegatoAsync(Richiesta, Autenticazione, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub GetAllegatoAsync(ByVal Richiesta As Messaggio_RichiestaAllegato, ByVal Autenticazione As Messaggio_AutenticazioneOperatore, ByVal userState As Object)
        If (Me.GetAllegatoOperationCompleted Is Nothing) Then
            Me.GetAllegatoOperationCompleted = AddressOf Me.OnGetAllegatoOperationCompleted
        End If
        Me.InvokeAsync("GetAllegato", New Object() {Richiesta, Autenticazione}, Me.GetAllegatoOperationCompleted, userState)
    End Sub
    
    Private Sub OnGetAllegatoOperationCompleted(ByVal arg As Object)
        If (Not (Me.GetAllegatoCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent GetAllegatoCompleted(Me, New GetAllegatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetTipologieProvvedimento", RequestNamespace:="http://www.intemaweb.com/provvedimentiamministrativi/types", ResponseElementName:="GetTipologieProvvedimentoRisposta", ResponseNamespace:="http://www.intemaweb.com/provvedimentiamministrativi/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GetTipologieProvvedimento(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal Richiesta As Messaggio_RichiestaGetTipologieProvvedimento) As <System.Xml.Serialization.XmlElementAttribute("Risposta", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> Messaggio_Risposta
        Dim results() As Object = Me.Invoke("GetTipologieProvvedimento", New Object() {Richiesta})
        Return CType(results(0),Messaggio_Risposta)
    End Function
    
    '''<remarks/>
    Public Function BeginGetTipologieProvvedimento(ByVal Richiesta As Messaggio_RichiestaGetTipologieProvvedimento, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GetTipologieProvvedimento", New Object() {Richiesta}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndGetTipologieProvvedimento(ByVal asyncResult As System.IAsyncResult) As Messaggio_Risposta
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Messaggio_Risposta)
    End Function
    
    '''<remarks/>
    Public Overloads Sub GetTipologieProvvedimentoAsync(ByVal Richiesta As Messaggio_RichiestaGetTipologieProvvedimento)
        Me.GetTipologieProvvedimentoAsync(Richiesta, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub GetTipologieProvvedimentoAsync(ByVal Richiesta As Messaggio_RichiestaGetTipologieProvvedimento, ByVal userState As Object)
        If (Me.GetTipologieProvvedimentoOperationCompleted Is Nothing) Then
            Me.GetTipologieProvvedimentoOperationCompleted = AddressOf Me.OnGetTipologieProvvedimentoOperationCompleted
        End If
        Me.InvokeAsync("GetTipologieProvvedimento", New Object() {Richiesta}, Me.GetTipologieProvvedimentoOperationCompleted, userState)
    End Sub
    
    Private Sub OnGetTipologieProvvedimentoOperationCompleted(ByVal arg As Object)
        If (Not (Me.GetTipologieProvvedimentoCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent GetTipologieProvvedimentoCompleted(Me, New GetTipologieProvvedimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaRicerca
    
    Private idAttoField As String
    
    Private annoField As String
    
    Private dataField As Messaggio_RichiestaRicercaData
    
    Private numeroAttoField As Messaggio_RichiestaRicercaNumeroAtto
    
    Private oggettoField As String
    
    Private paginazioneField As Messaggio_RichiestaRicercaPaginazione
    
    Private tipoAttoField As Messaggio_RichiestaTipoAtto
    
    Private leggeTrasparenzaField As Messaggio_RichiestaLeggeTrasparenza
    
    Private tipologiaProvvedimentoField As Messaggio_RichiestaTipologiaProvvedimento
    
    Private ufficioProponenteField As Messaggio_RichiestaRicercaUfficioProponente
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAtto() As String
        Get
            Return Me.idAttoField
        End Get
        Set
            Me.idAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property Anno() As String
        Get
            Return Me.annoField
        End Get
        Set
            Me.annoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Data() As Messaggio_RichiestaRicercaData
        Get
            Return Me.dataField
        End Get
        Set
            Me.dataField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NumeroAtto() As Messaggio_RichiestaRicercaNumeroAtto
        Get
            Return Me.numeroAttoField
        End Get
        Set
            Me.numeroAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Oggetto() As String
        Get
            Return Me.oggettoField
        End Get
        Set
            Me.oggettoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Paginazione() As Messaggio_RichiestaRicercaPaginazione
        Get
            Return Me.paginazioneField
        End Get
        Set
            Me.paginazioneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property TipoAtto() As Messaggio_RichiestaTipoAtto
        Get
            Return Me.tipoAttoField
        End Get
        Set
            Me.tipoAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property LeggeTrasparenza() As Messaggio_RichiestaLeggeTrasparenza
        Get
            Return Me.leggeTrasparenzaField
        End Get
        Set
            Me.leggeTrasparenzaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property TipologiaProvvedimento() As Messaggio_RichiestaTipologiaProvvedimento
        Get
            Return Me.tipologiaProvvedimentoField
        End Get
        Set
            Me.tipologiaProvvedimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property UfficioProponente() As Messaggio_RichiestaRicercaUfficioProponente
        Get
            Return Me.ufficioProponenteField
        End Get
        Set
            Me.ufficioProponenteField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaRicercaData
    
    Private dataAField As Date
    
    Private dataAFieldSpecified As Boolean
    
    Private dataDaField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
    Public Property DataA() As Date
        Get
            Return Me.dataAField
        End Get
        Set
            Me.dataAField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DataASpecified() As Boolean
        Get
            Return Me.dataAFieldSpecified
        End Get
        Set
            Me.dataAFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
    Public Property DataDa() As Date
        Get
            Return Me.dataDaField
        End Get
        Set
            Me.dataDaField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaGetTipologieProvvedimento
    
    Private tipologieField() As TipologiaProvvedimento_Types
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("tipologie", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property tipologie() As TipologiaProvvedimento_Types()
        Get
            Return Me.tipologieField
        End Get
        Set
            Me.tipologieField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class TipologiaProvvedimento_Types
    
    Private idField As String
    
    Private descrizioneField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property descrizione() As String
        Get
            Return Me.descrizioneField
        End Get
        Set
            Me.descrizioneField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaGetAllegato
    
    Private idAttoField As String
    
    Private idAllegatoField As String
    
    Private immagineAllegatoField() As Byte
    
    Private formatoImmagineAllegatoField As String
    
    Private nomeAllegatoField As String
    
    Private contentTypeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAtto() As String
        Get
            Return Me.idAttoField
        End Get
        Set
            Me.idAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAllegato() As String
        Get
            Return Me.idAllegatoField
        End Get
        Set
            Me.idAllegatoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
    Public Property ImmagineAllegato() As Byte()
        Get
            Return Me.immagineAllegatoField
        End Get
        Set
            Me.immagineAllegatoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property FormatoImmagineAllegato() As String
        Get
            Return Me.formatoImmagineAllegatoField
        End Get
        Set
            Me.formatoImmagineAllegatoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NomeAllegato() As String
        Get
            Return Me.nomeAllegatoField
        End Get
        Set
            Me.nomeAllegatoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ContentType() As String
        Get
            Return Me.contentTypeField
        End Get
        Set
            Me.contentTypeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaGetTipologieProvvedimento
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaAllegato
    
    Private idAttoField As String
    
    Private idAllegatoField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAtto() As String
        Get
            Return Me.idAttoField
        End Get
        Set
            Me.idAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAllegato() As String
        Get
            Return Me.idAllegatoField
        End Get
        Set
            Me.idAllegatoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaRicercaAttiPaginazione
    
    Private dimensionePaginaField As String
    
    Private paginaCorrenteField As String
    
    Private pagineTotaliField As String
    
    Private totaleAttiField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property DimensionePagina() As String
        Get
            Return Me.dimensionePaginaField
        End Get
        Set
            Me.dimensionePaginaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property PaginaCorrente() As String
        Get
            Return Me.paginaCorrenteField
        End Get
        Set
            Me.paginaCorrenteField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property PagineTotali() As String
        Get
            Return Me.pagineTotaliField
        End Get
        Set
            Me.pagineTotaliField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property TotaleAtti() As String
        Get
            Return Me.totaleAttiField
        End Get
        Set
            Me.totaleAttiField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Allegato_Types
    
    Private idAllegatoField As String
    
    Private nomeField As String
    
    Private formatoField As String
    
    Private documentoPrincipaleField As Boolean
    
    Private tipoField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAllegato() As String
        Get
            Return Me.idAllegatoField
        End Get
        Set
            Me.idAllegatoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Nome() As String
        Get
            Return Me.nomeField
        End Get
        Set
            Me.nomeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Formato() As String
        Get
            Return Me.formatoField
        End Get
        Set
            Me.formatoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DocumentoPrincipale() As Boolean
        Get
            Return Me.documentoPrincipaleField
        End Get
        Set
            Me.documentoPrincipaleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Tipo() As String
        Get
            Return Me.tipoField
        End Get
        Set
            Me.tipoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaRicercaAttiAttoAllegato
    
    Private idAttoField As String
    
    Private allegatoField() As Allegato_Types
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdAtto() As String
        Get
            Return Me.idAttoField
        End Get
        Set
            Me.idAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Allegato", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Allegato() As Allegato_Types()
        Get
            Return Me.allegatoField
        End Get
        Set
            Me.allegatoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Destinatario_Types
    
    Private idDestinatarioField As String
    
    Private isPersonaFisicaField As Boolean
    
    Private denominazioneField As String
    
    Private datiFiscaliField As Destinatario_TypesDatiFiscali
    
    Private luogoNascitaField As String
    
    Private dataNascitaField As String
    
    Private legaleRappresentanteField As String
    
    Private contrattoField As Contratto_Types
    
    Private isDatoSensibileField As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdDestinatario() As String
        Get
            Return Me.idDestinatarioField
        End Get
        Set
            Me.idDestinatarioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IsPersonaFisica() As Boolean
        Get
            Return Me.isPersonaFisicaField
        End Get
        Set
            Me.isPersonaFisicaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Denominazione() As String
        Get
            Return Me.denominazioneField
        End Get
        Set
            Me.denominazioneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DatiFiscali() As Destinatario_TypesDatiFiscali
        Get
            Return Me.datiFiscaliField
        End Get
        Set
            Me.datiFiscaliField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property LuogoNascita() As String
        Get
            Return Me.luogoNascitaField
        End Get
        Set
            Me.luogoNascitaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DataNascita() As String
        Get
            Return Me.dataNascitaField
        End Get
        Set
            Me.dataNascitaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property LegaleRappresentante() As String
        Get
            Return Me.legaleRappresentanteField
        End Get
        Set
            Me.legaleRappresentanteField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Contratto() As Contratto_Types
        Get
            Return Me.contrattoField
        End Get
        Set
            Me.contrattoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IsDatoSensibile() As Boolean
        Get
            Return Me.isDatoSensibileField
        End Get
        Set
            Me.isDatoSensibileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Destinatario_TypesDatiFiscali
    
    Private itemField As String
    
    Private itemElementNameField As ItemChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("CodiceFiscale", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlElementAttribute("PartitaIva", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
    Public Property Item() As String
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemElementName() As ItemChoiceType
        Get
            Return Me.itemElementNameField
        End Get
        Set
            Me.itemElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types", IncludeInSchema:=false)>  _
Public Enum ItemChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute(":CodiceFiscale")>  _
    CodiceFiscale
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute(":PartitaIva")>  _
    PartitaIva
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Contratto_Types
    
    Private id_ContrattoField As String
    
    Private numero_Repertorio_ContrattoField As String
    
    Private oggetto_ContrattoField As String
    
    Private lista_BeneficiariField() As Beneficiario_Types
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Id_Contratto() As String
        Get
            Return Me.id_ContrattoField
        End Get
        Set
            Me.id_ContrattoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Numero_Repertorio_Contratto() As String
        Get
            Return Me.numero_Repertorio_ContrattoField
        End Get
        Set
            Me.numero_Repertorio_ContrattoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Oggetto_Contratto() As String
        Get
            Return Me.oggetto_ContrattoField
        End Get
        Set
            Me.oggetto_ContrattoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlArrayItemAttribute("Beneficiario", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property Lista_Beneficiari() As Beneficiario_Types()
        Get
            Return Me.lista_BeneficiariField
        End Get
        Set
            Me.lista_BeneficiariField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Beneficiario_Types
    
    Private idBeneficiarioField As String
    
    Private idSedeField As String
    
    Private idLiquidazioneField As String
    
    Private isDatoSensibileField As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdBeneficiario() As String
        Get
            Return Me.idBeneficiarioField
        End Get
        Set
            Me.idBeneficiarioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdSede() As String
        Get
            Return Me.idSedeField
        End Get
        Set
            Me.idSedeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IdLiquidazione() As String
        Get
            Return Me.idLiquidazioneField
        End Get
        Set
            Me.idLiquidazioneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IsDatoSensibile() As Boolean
        Get
            Return Me.isDatoSensibileField
        End Get
        Set
            Me.isDatoSensibileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Tipologia_Provvedimento_Types
    
    Private idTipologiaProvvedimentoField As String
    
    Private descrizioneTipologiaProvvedimentoField As String
    
    Private lista_DestinatariField() As Destinatario_Types
    
    Private importoSpesaPrevistaField As Double
    
    Private importoSpesaPrevistaFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property IdTipologiaProvvedimento() As String
        Get
            Return Me.idTipologiaProvvedimentoField
        End Get
        Set
            Me.idTipologiaProvvedimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DescrizioneTipologiaProvvedimento() As String
        Get
            Return Me.descrizioneTipologiaProvvedimentoField
        End Get
        Set
            Me.descrizioneTipologiaProvvedimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlArrayItemAttribute("Destinatario", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property Lista_Destinatari() As Destinatario_Types()
        Get
            Return Me.lista_DestinatariField
        End Get
        Set
            Me.lista_DestinatariField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ImportoSpesaPrevista() As Double
        Get
            Return Me.importoSpesaPrevistaField
        End Get
        Set
            Me.importoSpesaPrevistaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ImportoSpesaPrevistaSpecified() As Boolean
        Get
            Return Me.importoSpesaPrevistaFieldSpecified
        End Get
        Set
            Me.importoSpesaPrevistaFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Legge_Trasparenza_Types
    
    Private autorizzazionePubblicazioneField As Boolean
    
    Private notePubblicazioneField As String
    
    Private normaAttribuzioneBeneficioField As String
    
    Private ufficioResponsabileProcedimentoField As String
    
    Private responsabileProcedimentoField As String
    
    Private modalitaIndividuazioneBeneficiarioField As String
    
    Private lista_ContrattiField() As Contratto_Types
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property AutorizzazionePubblicazione() As Boolean
        Get
            Return Me.autorizzazionePubblicazioneField
        End Get
        Set
            Me.autorizzazionePubblicazioneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotePubblicazione() As String
        Get
            Return Me.notePubblicazioneField
        End Get
        Set
            Me.notePubblicazioneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NormaAttribuzioneBeneficio() As String
        Get
            Return Me.normaAttribuzioneBeneficioField
        End Get
        Set
            Me.normaAttribuzioneBeneficioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property UfficioResponsabileProcedimento() As String
        Get
            Return Me.ufficioResponsabileProcedimentoField
        End Get
        Set
            Me.ufficioResponsabileProcedimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ResponsabileProcedimento() As String
        Get
            Return Me.responsabileProcedimentoField
        End Get
        Set
            Me.responsabileProcedimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ModalitaIndividuazioneBeneficiario() As String
        Get
            Return Me.modalitaIndividuazioneBeneficiarioField
        End Get
        Set
            Me.modalitaIndividuazioneBeneficiarioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlArrayItemAttribute("Contratto", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property Lista_Contratti() As Contratto_Types()
        Get
            Return Me.lista_ContrattiField
        End Get
        Set
            Me.lista_ContrattiField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaRicercaAttiAttoUfficioProponente
    
    Private codiceUfficioField As String
    
    Private descrizioneUfficioField As String
    
    Private codiceDipartimentoField As String
    
    Private descrizioneDipartimentoField As String
    
    Private responsabileField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property CodiceUfficio() As String
        Get
            Return Me.codiceUfficioField
        End Get
        Set
            Me.codiceUfficioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DescrizioneUfficio() As String
        Get
            Return Me.descrizioneUfficioField
        End Get
        Set
            Me.descrizioneUfficioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property CodiceDipartimento() As String
        Get
            Return Me.codiceDipartimentoField
        End Get
        Set
            Me.codiceDipartimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DescrizioneDipartimento() As String
        Get
            Return Me.descrizioneDipartimentoField
        End Get
        Set
            Me.descrizioneDipartimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Responsabile() As String
        Get
            Return Me.responsabileField
        End Get
        Set
            Me.responsabileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaRicercaAttiAtto
    
    Private dataAttoField As Date
    
    Private numeroCronologicoField As String
    
    Private numeroDefinitivoField As String
    
    Private oggettoField As String
    
    Private tipoAttoField As Tipo_Atto_Types
    
    Private ufficioProponenteField As Messaggio_RispostaRicercaAttiAttoUfficioProponente
    
    Private leggeTrasparenzaField As Legge_Trasparenza_Types
    
    Private tipologiaProvvedimentoField As Tipologia_Provvedimento_Types
    
    Private allegatiField As Messaggio_RispostaRicercaAttiAttoAllegato
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
    Public Property DataAtto() As Date
        Get
            Return Me.dataAttoField
        End Get
        Set
            Me.dataAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NumeroCronologico() As String
        Get
            Return Me.numeroCronologicoField
        End Get
        Set
            Me.numeroCronologicoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NumeroDefinitivo() As String
        Get
            Return Me.numeroDefinitivoField
        End Get
        Set
            Me.numeroDefinitivoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Oggetto() As String
        Get
            Return Me.oggettoField
        End Get
        Set
            Me.oggettoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property TipoAtto() As Tipo_Atto_Types
        Get
            Return Me.tipoAttoField
        End Get
        Set
            Me.tipoAttoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property UfficioProponente() As Messaggio_RispostaRicercaAttiAttoUfficioProponente
        Get
            Return Me.ufficioProponenteField
        End Get
        Set
            Me.ufficioProponenteField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property LeggeTrasparenza() As Legge_Trasparenza_Types
        Get
            Return Me.leggeTrasparenzaField
        End Get
        Set
            Me.leggeTrasparenzaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property TipologiaProvvedimento() As Tipologia_Provvedimento_Types
        Get
            Return Me.tipologiaProvvedimentoField
        End Get
        Set
            Me.tipologiaProvvedimentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Allegati() As Messaggio_RispostaRicercaAttiAttoAllegato
        Get
            Return Me.allegatiField
        End Get
        Set
            Me.allegatiField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Public Enum Tipo_Atto_Types
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("0")>  _
    Item0
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>  _
    Item1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>  _
    Item2
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaRicercaAtti
    
    Private attoField() As Messaggio_RispostaRicercaAttiAtto
    
    Private paginazioneField As Messaggio_RispostaRicercaAttiPaginazione
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Atto", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Atto() As Messaggio_RispostaRicercaAttiAtto()
        Get
            Return Me.attoField
        End Get
        Set
            Me.attoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Paginazione() As Messaggio_RispostaRicercaAttiPaginazione
        Get
            Return Me.paginazioneField
        End Get
        Set
            Me.paginazioneField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RispostaException
    
    Private codiceField As Object
    
    Private descrizioneField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Codice() As Object
        Get
            Return Me.codiceField
        End Get
        Set
            Me.codiceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Descrizione() As Object
        Get
            Return Me.descrizioneField
        End Get
        Set
            Me.descrizioneField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_Risposta
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Exception", GetType(Messaggio_RispostaException), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlElementAttribute("RispostaGetAllegato", GetType(Messaggio_RispostaGetAllegato), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlElementAttribute("RispostaGetTipologieProvvedimento", GetType(Messaggio_RispostaGetTipologieProvvedimento), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlElementAttribute("RispostaRicercaAtti", GetType(Messaggio_RispostaRicercaAtti), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_AutenticazioneOperatore
    
    Private cod_FiscaleField As String
    
    Private cod_UfficioField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Cod_Fiscale() As String
        Get
            Return Me.cod_FiscaleField
        End Get
        Set
            Me.cod_FiscaleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Cod_Ufficio() As String
        Get
            Return Me.cod_UfficioField
        End Get
        Set
            Me.cod_UfficioField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaRicercaUfficioProponente
    
    Private codiceField As String
    
    Private descrizioneField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Codice() As String
        Get
            Return Me.codiceField
        End Get
        Set
            Me.codiceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Descrizione() As String
        Get
            Return Me.descrizioneField
        End Get
        Set
            Me.descrizioneField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaTipologiaProvvedimento
    
    Private idTipologiaProvvedimentoField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property IdTipologiaProvvedimento() As String
        Get
            Return Me.idTipologiaProvvedimentoField
        End Get
        Set
            Me.idTipologiaProvvedimentoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaLeggeTrasparenza
    
    Private autorizzazionePubblicazioneField As Boolean
    
    Private autorizzazionePubblicazioneFieldSpecified As Boolean
    
    Private includiBeneficiariContrattoField As Boolean
    
    Private includiBeneficiariContrattoFieldSpecified As Boolean
    
    Private includiDettagliContrattoField As Boolean
    
    Private includiDettagliContrattoFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property AutorizzazionePubblicazione() As Boolean
        Get
            Return Me.autorizzazionePubblicazioneField
        End Get
        Set
            Me.autorizzazionePubblicazioneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property AutorizzazionePubblicazioneSpecified() As Boolean
        Get
            Return Me.autorizzazionePubblicazioneFieldSpecified
        End Get
        Set
            Me.autorizzazionePubblicazioneFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IncludiBeneficiariContratto() As Boolean
        Get
            Return Me.includiBeneficiariContrattoField
        End Get
        Set
            Me.includiBeneficiariContrattoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property IncludiBeneficiariContrattoSpecified() As Boolean
        Get
            Return Me.includiBeneficiariContrattoFieldSpecified
        End Get
        Set
            Me.includiBeneficiariContrattoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property IncludiDettagliContratto() As Boolean
        Get
            Return Me.includiDettagliContrattoField
        End Get
        Set
            Me.includiDettagliContrattoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property IncludiDettagliContrattoSpecified() As Boolean
        Get
            Return Me.includiDettagliContrattoFieldSpecified
        End Get
        Set
            Me.includiDettagliContrattoFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaTipoAtto
    
    Private tipoField As Tipo_Atto_Types
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Tipo() As Tipo_Atto_Types
        Get
            Return Me.tipoField
        End Get
        Set
            Me.tipoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaRicercaPaginazione
    
    Private paginaRichiestaField As String
    
    Private totalePerPaginaField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property PaginaRichiesta() As String
        Get
            Return Me.paginaRichiestaField
        End Get
        Set
            Me.paginaRichiestaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property TotalePerPagina() As String
        Get
            Return Me.totalePerPaginaField
        End Get
        Set
            Me.totalePerPaginaField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.intemaweb.com/provvedimentiamministrativi/types")>  _
Partial Public Class Messaggio_RichiestaRicercaNumeroAtto
    
    Private numeroAField As String
    
    Private numeroDaField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property NumeroA() As String
        Get
            Return Me.numeroAField
        End Get
        Set
            Me.numeroAField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
    Public Property NumeroDa() As String
        Get
            Return Me.numeroDaField
        End Get
        Set
            Me.numeroDaField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub RicercaAttiApprovatiCompletedEventHandler(ByVal sender As Object, ByVal e As RicercaAttiApprovatiCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class RicercaAttiApprovatiCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As Messaggio_Risposta
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),Messaggio_Risposta)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub GetAllegatoCompletedEventHandler(ByVal sender As Object, ByVal e As GetAllegatoCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class GetAllegatoCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As Messaggio_Risposta
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),Messaggio_Risposta)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub GetTipologieProvvedimentoCompletedEventHandler(ByVal sender As Object, ByVal e As GetTipologieProvvedimentoCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class GetTipologieProvvedimentoCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As Messaggio_Risposta
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),Messaggio_Risposta)
        End Get
        End Property
    End Class
End Namespace
