'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.3082
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://intemaweb.com/", ConfigurationName:="ServiceMergePDFSoap")>  _
Public Interface ServiceMergePDFSoap
    
    'CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento codOp dallo spazio dei nomi http://intemaweb.com/ non è contrassegnato come nillable
    <System.ServiceModel.OperationContractAttribute(Action:="http://intemaweb.com/MergeFile", ReplyAction:="*")>  _
    Function MergeFile(ByVal request As MergeFileRequest) As MergeFileResponse
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class MergeFileRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="MergeFile", [Namespace]:="http://intemaweb.com/", Order:=0)>  _
    Public Body As MergeFileRequestBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As MergeFileRequestBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://intemaweb.com/")>  _
Partial Public Class MergeFileRequestBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public codOp As String
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
    Public codDocumento As String
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
    Public fraseInTrasparenza As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal codOp As String, ByVal codDocumento As String, ByVal fraseInTrasparenza As String)
        MyBase.New
        Me.codOp = codOp
        Me.codDocumento = codDocumento
        Me.fraseInTrasparenza = fraseInTrasparenza
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class MergeFileResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="MergeFileResponse", [Namespace]:="http://intemaweb.com/", Order:=0)>  _
    Public Body As MergeFileResponseBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As MergeFileResponseBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://intemaweb.com/")>  _
Partial Public Class MergeFileResponseBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public MergeFileResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal MergeFileResult As String)
        MyBase.New
        Me.MergeFileResult = MergeFileResult
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface ServiceMergePDFSoapChannel
    Inherits ServiceMergePDFSoap, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class ServiceMergePDFSoapClient
    Inherits System.ServiceModel.ClientBase(Of ServiceMergePDFSoap)
    Implements ServiceMergePDFSoap
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function ServiceMergePDFSoap_MergeFile(ByVal request As MergeFileRequest) As MergeFileResponse Implements ServiceMergePDFSoap.MergeFile
        Return MyBase.Channel.MergeFile(request)
    End Function
    
    Public Function MergeFile(ByVal codOp As String, ByVal codDocumento As String, ByVal fraseInTrasparenza As String) As String
        Dim inValue As MergeFileRequest = New MergeFileRequest
        inValue.Body = New MergeFileRequestBody
        inValue.Body.codOp = codOp
        inValue.Body.codDocumento = codDocumento
        inValue.Body.fraseInTrasparenza = fraseInTrasparenza
        Dim retVal As MergeFileResponse = CType(Me,ServiceMergePDFSoap).MergeFile(inValue)
        Return retVal.Body.MergeFileResult
    End Function
End Class
