'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.5485
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class search

    '''<summary>
    '''Controllo pnlRicerca.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents pnlRicerca As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Controllo Titolo_Ricerca.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Titolo_Ricerca As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo labelTipoData.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents labelTipoData As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Controllo chkDataSeduta.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Public WithEvents chkDataSeduta As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Controllo Ricerca_i_documenti.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Ricerca_i_documenti As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo CalendarPopup1.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents CalendarPopup1 As Global.eWorld.UI.CalendarPopup

    '''<summary>
    '''Controllo alla_data.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents alla_data As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo CalendarPopup2.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents CalendarPopup2 As Global.eWorld.UI.CalendarPopup

    '''<summary>
    '''Controllo Numero.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Numero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo txtNumero.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txtNumero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo con_oggetto.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents con_oggetto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo txtOggettoRicerca.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents txtOggettoRicerca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo con_codiceCUP.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents con_codiceCUP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo con_codiceCIG.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents con_codiceCIG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo del_Dipartimento.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents del_Dipartimento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo dllDipartimenti.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents dllDipartimenti As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo dell_ufficio.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents dell_ufficio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo ddlUffici.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents ddlUffici As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo lblBeneficiario.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents lblBeneficiario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo TipologiaRicercaBeneficiario.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents TipologiaRicercaBeneficiario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo BeneficiarioTxt.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents BeneficiarioTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo lblTipologiaDocumento.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents lblTipologiaDocumento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo lblIsPubblicato.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents lblIsPubblicato As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo ddlAutorizPubblicazione.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents ddlAutorizPubblicazione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo lblDestinatario.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents lblDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controllo TipologiaRicercaDestinatario.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents TipologiaRicercaDestinatario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo DestinatarioTxt.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DestinatarioTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo btnAvviaRicercaOld.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents btnAvviaRicercaOld As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Controllo TipologiaRicercaBeneficiario2.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents TipologiaRicercaBeneficiario2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controllo BeneficiarioTxt2.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents BeneficiarioTxt2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo btnAvviaRicerca.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents btnAvviaRicerca As Global.System.Web.UI.WebControls.Button
End Class
