'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.5485
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da xsd, versione=2.0.50727.3038.
'
Namespace Intema.WS.Richiesta
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class NOTIFICAPROVVEDIMENTISICInput
        
        Private p_TIPODOCSICVARCHAR2INField As String
        
        Private p_STATONOTIFICAVARCHAR2INField As String
        
        Private p_NUMERODOCSICNUMBERINField As Double
        
        Private p_MESSAGGIOVARCHAR2OUTField As NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT
        
        Private p_IDFATTURANUMBERINField As Double
        
        Private p_IDATTOVARCHAR2INField As String
        
        Private p_ESITONUMBEROUTField As NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT
        
        Private p_DATADOCSICVARCHAR2INField As String
		
		 Private p_IMPORTONUMBERINField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_TIPODOCSIC-VARCHAR2-IN")>  _
        Public Property P_TIPODOCSICVARCHAR2IN() As String
            Get
                Return Me.p_TIPODOCSICVARCHAR2INField
            End Get
            Set
                Me.p_TIPODOCSICVARCHAR2INField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_STATONOTIFICA-VARCHAR2-IN")>  _
        Public Property P_STATONOTIFICAVARCHAR2IN() As String
            Get
                Return Me.p_STATONOTIFICAVARCHAR2INField
            End Get
            Set
                Me.p_STATONOTIFICAVARCHAR2INField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_NUMERODOCSIC-NUMBER-IN")>  _
        Public Property P_NUMERODOCSICNUMBERIN() As Double
            Get
                Return Me.p_NUMERODOCSICNUMBERINField
            End Get
            Set
                Me.p_NUMERODOCSICNUMBERINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_MESSAGGIO-VARCHAR2-OUT")>  _
        Public Property P_MESSAGGIOVARCHAR2OUT() As NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT
            Get
                Return Me.p_MESSAGGIOVARCHAR2OUTField
            End Get
            Set
                Me.p_MESSAGGIOVARCHAR2OUTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_IDFATTURA-NUMBER-IN")>  _
        Public Property P_IDFATTURANUMBERIN() As Double
            Get
                Return Me.p_IDFATTURANUMBERINField
            End Get
            Set
                Me.p_IDFATTURANUMBERINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_IDATTO-VARCHAR2-IN")>  _
        Public Property P_IDATTOVARCHAR2IN() As String
            Get
                Return Me.p_IDATTOVARCHAR2INField
            End Get
            Set
                Me.p_IDATTOVARCHAR2INField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_ESITO-NUMBER-OUT")>  _
        Public Property P_ESITONUMBEROUT() As NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT
            Get
                Return Me.p_ESITONUMBEROUTField
            End Get
            Set
                Me.p_ESITONUMBEROUTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_DATADOCSIC-VARCHAR2-IN")>  _
        Public Property P_DATADOCSICVARCHAR2IN() As String
            Get
                Return Me.p_DATADOCSICVARCHAR2INField
            End Get
            Set
                Me.p_DATADOCSICVARCHAR2INField = value
            End Set
        End Property
		
		'''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("P_IMPORTO-NUMBER-IN")>  _
        Public Property P_IMPORTONUMBERIN() As Double
            Get
                Return Me.p_IMPORTONUMBERINField
            End Get
            Set
                Me.p_IMPORTONUMBERINField = value
            End Set
        End Property
		
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class NOTIFICAPROVVEDIMENTISICInputP_MESSAGGIOVARCHAR2OUT
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class NOTIFICAPROVVEDIMENTISICInputP_ESITONUMBEROUT
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class NOTIFICAPROVVEDIMENTISICOutput
        
        Private p_MESSAGGIOField As String
        
        Private p_ESITOField As Double
        
        '''<remarks/>
        Public Property P_MESSAGGIO() As String
            Get
                Return Me.p_MESSAGGIOField
            End Get
            Set
                Me.p_MESSAGGIOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property P_ESITO() As Double
            Get
                Return Me.p_ESITOField
            End Get
            Set
                Me.p_ESITOField = value
            End Set
        End Property
    End Class
End Namespace
