'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.5466
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

Namespace Intema.WS.Ana.Richiesta
    '
    'Codice sorgente generato automaticamente da xsd, versione=2.0.50727.3038.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlRootAttribute("Messaggio_Richiesta", [Namespace]:="", IsNullable:=False)> _
    Partial Public Class MessaggioRichiesta_Types

        Private intestazioneField As Intestazione_Types

        Private richiestaField As Richiesta_Types

        '''<remarks/>
        Public Property Intestazione() As Intestazione_Types
            Get
                Return Me.intestazioneField
            End Get
            Set(ByVal value As Intestazione_Types)
                Me.intestazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Richiesta() As Richiesta_Types
            Get
                Return Me.richiestaField
            End Get
            Set(ByVal value As Richiesta_Types)
                Me.richiestaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class Intestazione_Types

        Private infoMittDestField As String

        Private applicazioneField As String

        '''<remarks/>
        Public Property InfoMittDest() As String
            Get
                Return Me.infoMittDestField
            End Get
            Set(ByVal value As String)
                Me.infoMittDestField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Applicazione() As String
            Get
                Return Me.applicazioneField
            End Get
            Set(ByVal value As String)
                Me.applicazioneField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ModificaContoBancario_Types

        Private idAnagraficaField As String

        Private idSedeField As String

        Private idContoCorrenteField As String

        Private contoCorrenteField As String

        Private modalitaPrincipaleField As ModificaContoBancario_TypesModalitaPrincipale

        Private cINField As String

        Private iBANField As String

        Private codiceFiscaleOperatoreField As String

        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set(ByVal value As String)
                Me.idAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set(ByVal value As String)
                Me.idSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IdContoCorrente() As String
            Get
                Return Me.idContoCorrenteField
            End Get
            Set(ByVal value As String)
                Me.idContoCorrenteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ContoCorrente() As String
            Get
                Return Me.contoCorrenteField
            End Get
            Set(ByVal value As String)
                Me.contoCorrenteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ModalitaPrincipale() As ModificaContoBancario_TypesModalitaPrincipale
            Get
                Return Me.modalitaPrincipaleField
            End Get
            Set(ByVal value As ModificaContoBancario_TypesModalitaPrincipale)
                Me.modalitaPrincipaleField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CIN() As String
            Get
                Return Me.cINField
            End Get
            Set(ByVal value As String)
                Me.cINField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IBAN() As String
            Get
                Return Me.iBANField
            End Get
            Set(ByVal value As String)
                Me.iBANField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleOperatore() As String
            Get
                Return Me.codiceFiscaleOperatoreField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleOperatoreField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaContoBancario_TypesModalitaPrincipale

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ModificaSede_Types

        Private idAnagraficaField As String

        Private idSedeField As String

        Private indirizzoField As String

        Private comuneField As String

        Private cAPField As String

        Private telefonoField As String

        Private eMailField As String

        Private faxField As String

        Private bolloField As ModificaSede_TypesBollo

        Private bolloFieldSpecified As Boolean

        Private nomeSedeField As String

        Private tipoPagamentoField As String

        Private codiceFiscaleOperatoreField As String

        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set(ByVal value As String)
                Me.idAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set(ByVal value As String)
                Me.idSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set(ByVal value As String)
                Me.indirizzoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Comune() As String
            Get
                Return Me.comuneField
            End Get
            Set(ByVal value As String)
                Me.comuneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAP() As String
            Get
                Return Me.cAPField
            End Get
            Set(ByVal value As String)
                Me.cAPField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set(ByVal value As String)
                Me.telefonoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EMail() As String
            Get
                Return Me.eMailField
            End Get
            Set(ByVal value As String)
                Me.eMailField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set(ByVal value As String)
                Me.faxField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Bollo() As ModificaSede_TypesBollo
            Get
                Return Me.bolloField
            End Get
            Set(ByVal value As ModificaSede_TypesBollo)
                Me.bolloField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property BolloSpecified() As Boolean
            Get
                Return Me.bolloFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.bolloFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NomeSede() As String
            Get
                Return Me.nomeSedeField
            End Get
            Set(ByVal value As String)
                Me.nomeSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoPagamento() As String
            Get
                Return Me.tipoPagamentoField
            End Get
            Set(ByVal value As String)
                Me.tipoPagamentoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleOperatore() As String
            Get
                Return Me.codiceFiscaleOperatoreField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleOperatoreField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaSede_TypesBollo

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ModificaAnagrafica_Types

        Private idAnagraficaField As String

        Private tipoAnagraficaField As ModificaAnagrafica_TypesTipoAnagrafica

        Private partitaIvaField As String

        Private denominazioneField As String

        Private cognomeLRField As String

        Private nomeLRField As String

        Private sessoLRField As ModificaAnagrafica_TypesSessoLR

        Private sessoLRFieldSpecified As Boolean

        Private comuneNSLRField As String

        Private dataNascitaLRField As Date

        Private dataNascitaLRFieldSpecified As Boolean

        Private indirizzoLRField As String

        Private comuneRESLRField As String

        Private cAPRESLRField As String

        Private codiceFiscaleLRField As String

        Private codiceFiscaleField As String

        Private cognomeField As String

        Private nomeField As String

        Private altriNomiField As String

        Private sessoField As ModificaAnagrafica_TypesSesso

        Private sessoFieldSpecified As Boolean

        Private comuneNSField As String

        Private dataNascitaField As Date

        Private dataNascitaFieldSpecified As Boolean

        Private pignoramentoField As ModificaAnagrafica_TypesPignoramento

        Private pignoramentoFieldSpecified As Boolean

        Private notaPignoramentoField As String

        Private esteroField As ModificaAnagrafica_TypesEstero

        Private esteroFieldSpecified As Boolean

        Private commissioniField As ModificaAnagrafica_TypesCommissioni

        Private commissioniFieldSpecified As Boolean

        Private codiceFiscaleOperatoreField As String

        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set(ByVal value As String)
                Me.idAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoAnagrafica() As ModificaAnagrafica_TypesTipoAnagrafica
            Get
                Return Me.tipoAnagraficaField
            End Get
            Set(ByVal value As ModificaAnagrafica_TypesTipoAnagrafica)
                Me.tipoAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PartitaIva() As String
            Get
                Return Me.partitaIvaField
            End Get
            Set(ByVal value As String)
                Me.partitaIvaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Denominazione() As String
            Get
                Return Me.denominazioneField
            End Get
            Set(ByVal value As String)
                Me.denominazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CognomeLR() As String
            Get
                Return Me.cognomeLRField
            End Get
            Set(ByVal value As String)
                Me.cognomeLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NomeLR() As String
            Get
                Return Me.nomeLRField
            End Get
            Set(ByVal value As String)
                Me.nomeLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SessoLR() As ModificaAnagrafica_TypesSessoLR
            Get
                Return Me.sessoLRField
            End Get
            Set(ByVal value As ModificaAnagrafica_TypesSessoLR)
                Me.sessoLRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property SessoLRSpecified() As Boolean
            Get
                Return Me.sessoLRFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.sessoLRFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComuneNSLR() As String
            Get
                Return Me.comuneNSLRField
            End Get
            Set(ByVal value As String)
                Me.comuneNSLRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property DataNascitaLR() As Date
            Get
                Return Me.dataNascitaLRField
            End Get
            Set(ByVal value As Date)
                Me.dataNascitaLRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DataNascitaLRSpecified() As Boolean
            Get
                Return Me.dataNascitaLRFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dataNascitaLRFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IndirizzoLR() As String
            Get
                Return Me.indirizzoLRField
            End Get
            Set(ByVal value As String)
                Me.indirizzoLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComuneRESLR() As String
            Get
                Return Me.comuneRESLRField
            End Get
            Set(ByVal value As String)
                Me.comuneRESLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAPRESLR() As String
            Get
                Return Me.cAPRESLRField
            End Get
            Set(ByVal value As String)
                Me.cAPRESLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleLR() As String
            Get
                Return Me.codiceFiscaleLRField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscale() As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Cognome() As String
            Get
                Return Me.cognomeField
            End Get
            Set(ByVal value As String)
                Me.cognomeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set(ByVal value As String)
                Me.nomeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AltriNomi() As String
            Get
                Return Me.altriNomiField
            End Get
            Set(ByVal value As String)
                Me.altriNomiField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Sesso() As ModificaAnagrafica_TypesSesso
            Get
                Return Me.sessoField
            End Get
            Set(ByVal value As ModificaAnagrafica_TypesSesso)
                Me.sessoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property SessoSpecified() As Boolean
            Get
                Return Me.sessoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.sessoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComuneNS() As String
            Get
                Return Me.comuneNSField
            End Get
            Set(ByVal value As String)
                Me.comuneNSField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property DataNascita() As Date
            Get
                Return Me.dataNascitaField
            End Get
            Set(ByVal value As Date)
                Me.dataNascitaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DataNascitaSpecified() As Boolean
            Get
                Return Me.dataNascitaFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dataNascitaFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Pignoramento() As ModificaAnagrafica_TypesPignoramento
            Get
                Return Me.pignoramentoField
            End Get
            Set(ByVal value As ModificaAnagrafica_TypesPignoramento)
                Me.pignoramentoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property PignoramentoSpecified() As Boolean
            Get
                Return Me.pignoramentoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.pignoramentoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NotaPignoramento() As String
            Get
                Return Me.notaPignoramentoField
            End Get
            Set(ByVal value As String)
                Me.notaPignoramentoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Estero() As ModificaAnagrafica_TypesEstero
            Get
                Return Me.esteroField
            End Get
            Set(ByVal value As ModificaAnagrafica_TypesEstero)
                Me.esteroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property EsteroSpecified() As Boolean
            Get
                Return Me.esteroFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.esteroFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Commissioni() As ModificaAnagrafica_TypesCommissioni
            Get
                Return Me.commissioniField
            End Get
            Set(ByVal value As ModificaAnagrafica_TypesCommissioni)
                Me.commissioniField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property CommissioniSpecified() As Boolean
            Get
                Return Me.commissioniFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.commissioniFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleOperatore() As String
            Get
                Return Me.codiceFiscaleOperatoreField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleOperatoreField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaAnagrafica_TypesTipoAnagrafica

        '''<remarks/>
        F

        '''<remarks/>
        G
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaAnagrafica_TypesSessoLR

        '''<remarks/>
        F

        '''<remarks/>
        M
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaAnagrafica_TypesSesso

        '''<remarks/>
        F

        '''<remarks/>
        M
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaAnagrafica_TypesPignoramento

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaAnagrafica_TypesEstero

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum ModificaAnagrafica_TypesCommissioni

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class InterrogaComuni_Types

        Private nomeComuneField As String

        '''<remarks/>
        Public Property NomeComune() As String
            Get
                Return Me.nomeComuneField
            End Get
            Set(ByVal value As String)
                Me.nomeComuneField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class CreaContoBancario_Types

        Private idAnagraficaField As String

        Private idSedeField As String

        Private datiBancariField As DatiBancari_Types

        Private codiceFiscaleOperatoreField As String

        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set(ByVal value As String)
                Me.idAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set(ByVal value As String)
                Me.idSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DatiBancari() As DatiBancari_Types
            Get
                Return Me.datiBancariField
            End Get
            Set(ByVal value As DatiBancari_Types)
                Me.datiBancariField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleOperatore() As String
            Get
                Return Me.codiceFiscaleOperatoreField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleOperatoreField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class DatiBancari_Types

        Private nomeBancaField As String

        Private contoCorrenteField As String

        Private modalitaPrincipaleField As DatiBancari_TypesModalitaPrincipale

        Private modalitaPrincipaleFieldSpecified As Boolean

        Private sedeAgenziaField As String

        Private indirizzoField As String

        Private cittaField As String

        Private cAPField As String

        Private provinciaField As String

        Private aBIField As String

        Private cABField As String

        Private cINField As String

        Private iBANField As String

        '''<remarks/>
        Public Property NomeBanca() As String
            Get
                Return Me.nomeBancaField
            End Get
            Set(ByVal value As String)
                Me.nomeBancaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ContoCorrente() As String
            Get
                Return Me.contoCorrenteField
            End Get
            Set(ByVal value As String)
                Me.contoCorrenteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ModalitaPrincipale() As DatiBancari_TypesModalitaPrincipale
            Get
                Return Me.modalitaPrincipaleField
            End Get
            Set(ByVal value As DatiBancari_TypesModalitaPrincipale)
                Me.modalitaPrincipaleField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ModalitaPrincipaleSpecified() As Boolean
            Get
                Return Me.modalitaPrincipaleFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.modalitaPrincipaleFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SedeAgenzia() As String
            Get
                Return Me.sedeAgenziaField
            End Get
            Set(ByVal value As String)
                Me.sedeAgenziaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set(ByVal value As String)
                Me.indirizzoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Citta() As String
            Get
                Return Me.cittaField
            End Get
            Set(ByVal value As String)
                Me.cittaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAP() As String
            Get
                Return Me.cAPField
            End Get
            Set(ByVal value As String)
                Me.cAPField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set(ByVal value As String)
                Me.provinciaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ABI() As String
            Get
                Return Me.aBIField
            End Get
            Set(ByVal value As String)
                Me.aBIField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAB() As String
            Get
                Return Me.cABField
            End Get
            Set(ByVal value As String)
                Me.cABField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CIN() As String
            Get
                Return Me.cINField
            End Get
            Set(ByVal value As String)
                Me.cINField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IBAN() As String
            Get
                Return Me.iBANField
            End Get
            Set(ByVal value As String)
                Me.iBANField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum DatiBancari_TypesModalitaPrincipale

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class CreaSede_Types

        Private idAnagraficaField As String

        Private sedeField As Sede_Types

        Private datiBancariField As DatiBancari_Types

        Private codiceFiscaleOperatoreField As String

        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set(ByVal value As String)
                Me.idAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Sede() As Sede_Types
            Get
                Return Me.sedeField
            End Get
            Set(ByVal value As Sede_Types)
                Me.sedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DatiBancari() As DatiBancari_Types
            Get
                Return Me.datiBancariField
            End Get
            Set(ByVal value As DatiBancari_Types)
                Me.datiBancariField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleOperatore() As String
            Get
                Return Me.codiceFiscaleOperatoreField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleOperatoreField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class Sede_Types

        Private indirizzoField As String

        Private comuneField As String

        Private cAPField As String

        Private telefonoField As String

        Private eMailField As String

        Private faxField As String

        Private bolloField As Sede_TypesBollo

        Private bolloFieldSpecified As Boolean

        Private nomeSedeField As String

        Private tipoPagamentoField As String

        '''<remarks/>
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set(ByVal value As String)
                Me.indirizzoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Comune() As String
            Get
                Return Me.comuneField
            End Get
            Set(ByVal value As String)
                Me.comuneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAP() As String
            Get
                Return Me.cAPField
            End Get
            Set(ByVal value As String)
                Me.cAPField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set(ByVal value As String)
                Me.telefonoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EMail() As String
            Get
                Return Me.eMailField
            End Get
            Set(ByVal value As String)
                Me.eMailField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set(ByVal value As String)
                Me.faxField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Bollo() As Sede_TypesBollo
            Get
                Return Me.bolloField
            End Get
            Set(ByVal value As Sede_TypesBollo)
                Me.bolloField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property BolloSpecified() As Boolean
            Get
                Return Me.bolloFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.bolloFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NomeSede() As String
            Get
                Return Me.nomeSedeField
            End Get
            Set(ByVal value As String)
                Me.nomeSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoPagamento() As String
            Get
                Return Me.tipoPagamentoField
            End Get
            Set(ByVal value As String)
                Me.tipoPagamentoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Sede_TypesBollo

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class CreaAnagrafica_Types

        Private anagraficaField As Anagrafica_Types

        Private codiceFiscaleOperatoreField As String

        '''<remarks/>
        Public Property Anagrafica() As Anagrafica_Types
            Get
                Return Me.anagraficaField
            End Get
            Set(ByVal value As Anagrafica_Types)
                Me.anagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleOperatore() As String
            Get
                Return Me.codiceFiscaleOperatoreField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleOperatoreField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class Anagrafica_Types

        Private tipoAnagraficaField As Anagrafica_TypesTipoAnagrafica

        Private partitaIvaField As String

        Private denominazioneField As String

        Private cognomeLRField As String

        Private nomeLRField As String

        Private sessoLRField As Anagrafica_TypesSessoLR

        Private sessoLRFieldSpecified As Boolean

        Private comuneNSLRField As String

        Private dataNascitaLRField As Date

        Private dataNascitaLRFieldSpecified As Boolean

        Private indirizzoLRField As String

        Private comuneRESLRField As String

        Private cAPRESLRField As String

        Private codiceFiscaleLRField As String

        Private codiceFiscaleField As String

        Private cognomeField As String

        Private nomeField As String

        Private altriNomiField As String

        Private sessoField As Anagrafica_TypesSesso

        Private sessoFieldSpecified As Boolean

        Private comuneNSField As String

        Private dataNascitaField As Date

        Private dataNascitaFieldSpecified As Boolean

        Private pignoramentoField As Anagrafica_TypesPignoramento

        Private pignoramentoFieldSpecified As Boolean

        Private notaPignoramentoField As String

        Private esteroField As Anagrafica_TypesEstero

        Private esteroFieldSpecified As Boolean

        Private commissioniField As Anagrafica_TypesCommissioni

        Private commissioniFieldSpecified As Boolean

        Private sedeField As Sede_Types

        Private datiBancariField As DatiBancari_Types

        '''<remarks/>
        Public Property TipoAnagrafica() As Anagrafica_TypesTipoAnagrafica
            Get
                Return Me.tipoAnagraficaField
            End Get
            Set(ByVal value As Anagrafica_TypesTipoAnagrafica)
                Me.tipoAnagraficaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PartitaIva() As String
            Get
                Return Me.partitaIvaField
            End Get
            Set(ByVal value As String)
                Me.partitaIvaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Denominazione() As String
            Get
                Return Me.denominazioneField
            End Get
            Set(ByVal value As String)
                Me.denominazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CognomeLR() As String
            Get
                Return Me.cognomeLRField
            End Get
            Set(ByVal value As String)
                Me.cognomeLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NomeLR() As String
            Get
                Return Me.nomeLRField
            End Get
            Set(ByVal value As String)
                Me.nomeLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SessoLR() As Anagrafica_TypesSessoLR
            Get
                Return Me.sessoLRField
            End Get
            Set(ByVal value As Anagrafica_TypesSessoLR)
                Me.sessoLRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property SessoLRSpecified() As Boolean
            Get
                Return Me.sessoLRFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.sessoLRFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComuneNSLR() As String
            Get
                Return Me.comuneNSLRField
            End Get
            Set(ByVal value As String)
                Me.comuneNSLRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property DataNascitaLR() As Date
            Get
                Return Me.dataNascitaLRField
            End Get
            Set(ByVal value As Date)
                Me.dataNascitaLRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DataNascitaLRSpecified() As Boolean
            Get
                Return Me.dataNascitaLRFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dataNascitaLRFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IndirizzoLR() As String
            Get
                Return Me.indirizzoLRField
            End Get
            Set(ByVal value As String)
                Me.indirizzoLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComuneRESLR() As String
            Get
                Return Me.comuneRESLRField
            End Get
            Set(ByVal value As String)
                Me.comuneRESLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAPRESLR() As String
            Get
                Return Me.cAPRESLRField
            End Get
            Set(ByVal value As String)
                Me.cAPRESLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscaleLR() As String
            Get
                Return Me.codiceFiscaleLRField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleLRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceFiscale() As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set(ByVal value As String)
                Me.codiceFiscaleField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Cognome() As String
            Get
                Return Me.cognomeField
            End Get
            Set(ByVal value As String)
                Me.cognomeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set(ByVal value As String)
                Me.nomeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AltriNomi() As String
            Get
                Return Me.altriNomiField
            End Get
            Set(ByVal value As String)
                Me.altriNomiField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Sesso() As Anagrafica_TypesSesso
            Get
                Return Me.sessoField
            End Get
            Set(ByVal value As Anagrafica_TypesSesso)
                Me.sessoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property SessoSpecified() As Boolean
            Get
                Return Me.sessoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.sessoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComuneNS() As String
            Get
                Return Me.comuneNSField
            End Get
            Set(ByVal value As String)
                Me.comuneNSField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property DataNascita() As Date
            Get
                Return Me.dataNascitaField
            End Get
            Set(ByVal value As Date)
                Me.dataNascitaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DataNascitaSpecified() As Boolean
            Get
                Return Me.dataNascitaFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dataNascitaFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Pignoramento() As Anagrafica_TypesPignoramento
            Get
                Return Me.pignoramentoField
            End Get
            Set(ByVal value As Anagrafica_TypesPignoramento)
                Me.pignoramentoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property PignoramentoSpecified() As Boolean
            Get
                Return Me.pignoramentoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.pignoramentoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NotaPignoramento() As String
            Get
                Return Me.notaPignoramentoField
            End Get
            Set(ByVal value As String)
                Me.notaPignoramentoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Estero() As Anagrafica_TypesEstero
            Get
                Return Me.esteroField
            End Get
            Set(ByVal value As Anagrafica_TypesEstero)
                Me.esteroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property EsteroSpecified() As Boolean
            Get
                Return Me.esteroFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.esteroFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Commissioni() As Anagrafica_TypesCommissioni
            Get
                Return Me.commissioniField
            End Get
            Set(ByVal value As Anagrafica_TypesCommissioni)
                Me.commissioniField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property CommissioniSpecified() As Boolean
            Get
                Return Me.commissioniFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.commissioniFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Sede() As Sede_Types
            Get
                Return Me.sedeField
            End Get
            Set(ByVal value As Sede_Types)
                Me.sedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DatiBancari() As DatiBancari_Types
            Get
                Return Me.datiBancariField
            End Get
            Set(ByVal value As DatiBancari_Types)
                Me.datiBancariField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Anagrafica_TypesTipoAnagrafica

        '''<remarks/>
        F

        '''<remarks/>
        G
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Anagrafica_TypesSessoLR

        '''<remarks/>
        F

        '''<remarks/>
        M
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Anagrafica_TypesSesso

        '''<remarks/>
        F

        '''<remarks/>
        M
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Anagrafica_TypesPignoramento

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Anagrafica_TypesEstero

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Public Enum Anagrafica_TypesCommissioni

        '''<remarks/>
        S

        '''<remarks/>
        N
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class VerificaAnagrafica_Types

        Private anagraficaField As Anagrafica_Types

        '''<remarks/>
        Public Property Anagrafica() As Anagrafica_Types
            Get
                Return Me.anagraficaField
            End Get
            Set(ByVal value As Anagrafica_Types)
                Me.anagraficaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class InterrogaAnagrafica_Types

        Private itemField As String

        Private itemElementNameField As ItemChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CodiceFiscale", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("IdAnagrafica", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("NumeroContratto", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("PartitaIva", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As String)
                Me.itemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set(ByVal value As ItemChoiceType)
                Me.itemElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema:=False)> _
    Public Enum ItemChoiceType

        '''<remarks/>
        CodiceFiscale

        '''<remarks/>
        Denominazione

        '''<remarks/>
        IdAnagrafica

        '''<remarks/>
        NumeroContratto

        '''<remarks/>
        PartitaIva
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class Richiesta_Types

        Private itemField As Object

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CreaAnagrafica", GetType(CreaAnagrafica_Types)), _
         System.Xml.Serialization.XmlElementAttribute("CreaContoBancario", GetType(CreaContoBancario_Types)), _
         System.Xml.Serialization.XmlElementAttribute("CreaSede", GetType(CreaSede_Types)), _
         System.Xml.Serialization.XmlElementAttribute("InterrogaAnagrafica", GetType(InterrogaAnagrafica_Types)), _
         System.Xml.Serialization.XmlElementAttribute("InterrogaComuni", GetType(InterrogaComuni_Types)), _
         System.Xml.Serialization.XmlElementAttribute("ModificaAnagrafica", GetType(ModificaAnagrafica_Types)), _
         System.Xml.Serialization.XmlElementAttribute("ModificaContoBancario", GetType(ModificaContoBancario_Types)), _
         System.Xml.Serialization.XmlElementAttribute("ModificaSede", GetType(ModificaSede_Types)), _
         System.Xml.Serialization.XmlElementAttribute("VerificaAnagrafica", GetType(VerificaAnagrafica_Types))> _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As Object)
                Me.itemField = Value
            End Set
        End Property
    End Class
End Namespace
