'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.9148
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da xsd, versione=2.0.50727.3038.
'
Namespace Intema.WS.Richiesta
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlRootAttribute("Messaggio_Richiesta", [Namespace]:="", IsNullable:=false)>  _
    Partial Public Class MessaggioRichiesta_Types
        
        Private intestazioneField As Intestazione_Types
        
        Private richiestaField As Richiesta_Types
        
        '''<remarks/>
        Public Property Intestazione() As Intestazione_Types
            Get
                Return Me.intestazioneField
            End Get
            Set
                Me.intestazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Richiesta() As Richiesta_Types
            Get
                Return Me.richiestaField
            End Get
            Set
                Me.richiestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Intestazione_Types
        
        Private infoMittDestField As String
        
        Private applicazioneField As String
        
        '''<remarks/>
        Public Property InfoMittDest() As String
            Get
                Return Me.infoMittDestField
            End Get
            Set
                Me.infoMittDestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applicazione() As String
            Get
                Return Me.applicazioneField
            End Get
            Set
                Me.applicazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazionePCF_Types
        
        Private annoField As String
        
        Private codiceCapitoloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property Anno() As String
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneCodiciSiope_Types
        
        Private annoField As String
        
        Private codiceCapitoloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property Anno() As String
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogaMandatiBeneficiariAtto_Types
        
        Private tipoAttoField As String
        
        Private numeroAttoField As String
        
        Private dataAttoField As Date
        
        Private ufficioField As String
        
        Private numeroLiquidazioneField As Long
        
        Private numeroLiquidazioneFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property TipoAtto() As String
            Get
                Return Me.tipoAttoField
            End Get
            Set
                Me.tipoAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroAtto() As String
            Get
                Return Me.numeroAttoField
            End Get
            Set
                Me.numeroAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DataAtto() As Date
            Get
                Return Me.dataAttoField
            End Get
            Set
                Me.dataAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ufficio() As String
            Get
                Return Me.ufficioField
            End Get
            Set
                Me.ufficioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroLiquidazione() As Long
            Get
                Return Me.numeroLiquidazioneField
            End Get
            Set
                Me.numeroLiquidazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NumeroLiquidazioneSpecified() As Boolean
            Get
                Return Me.numeroLiquidazioneFieldSpecified
            End Get
            Set
                Me.numeroLiquidazioneFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogaBeneficiariLiq_Types
        
        Private numeroLiquidazioneField As String
        
        '''<remarks/>
        Public Property NumeroLiquidazione() As String
            Get
                Return Me.numeroLiquidazioneField
            End Get
            Set
                Me.numeroLiquidazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogaReversaliCollegabili_Types
        
        Private annoBilancioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoBilancio() As String
            Get
                Return Me.annoBilancioField
            End Get
            Set
                Me.annoBilancioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogaCapitoloEntrata_Types
        
        Private annoBilancioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoBilancio() As String
            Get
                Return Me.annoBilancioField
            End Get
            Set
                Me.annoBilancioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogaCodiceSiope_Types
        
        Private annoBilancioField As String
        
        Private codiceCapitoloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoBilancio() As String
            Get
                Return Me.annoBilancioField
            End Get
            Set
                Me.annoBilancioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneListaContratti_Types
        
        Private chiaveField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Chiave")>  _
        Public Property Chiave() As String()
            Get
                Return Me.chiaveField
            End Get
            Set
                Me.chiaveField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneContratti_Types
        
        Private numeroContrattoField As String
        
        Private oggettoContrattoField As String
        
        '''<remarks/>
        Public Property NumeroContratto() As String
            Get
                Return Me.numeroContrattoField
            End Get
            Set
                Me.numeroContrattoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OggettoContratto() As String
            Get
                Return Me.oggettoContrattoField
            End Get
            Set
                Me.oggettoContrattoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneMandatiTrasparenza_Types
        
        Private annoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property Anno() As String
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerificaStato_Types
        
        Private annoFinanziarioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoFinanziario() As String
            Get
                Return Me.annoFinanziarioField
            End Get
            Set
                Me.annoFinanziarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DisponibilitaImpegno_Types
        
        Private numeroImpegnoField As String
        
        '''<remarks/>
        Public Property NumeroImpegno() As String
            Get
                Return Me.numeroImpegnoField
            End Get
            Set
                Me.numeroImpegnoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReversaleColl_Types
        
        Private numeroReversaleField As String
        
        Private importoReversaleField As Double
        
        '''<remarks/>
        Public Property NumeroReversale() As String
            Get
                Return Me.numeroReversaleField
            End Get
            Set
                Me.numeroReversaleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportoReversale() As Double
            Get
                Return Me.importoReversaleField
            End Get
            Set
                Me.importoReversaleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Beneficiario_Types
        
        Private codiceBeneficiarioField As String
        
        Private codiceSedeField As String
        
        Private codiceTipoPagamentoField As String
        
        Private codiceContoCorrenteField As String
        
        Private codiceSIOPEField As String
        
        Private codiceSIOPEAggiuntivoField As String
        
        Private codiceCUPField As String
        
        Private codiceCIGField As String
        
        Private esenzCommBonificoField As String
        
        Private stampaAvvisoField As String
        
        Private bolloField As String
        
        Private importoLordoField As Double
        
        Private importoLordoFieldSpecified As Boolean
        
        Private imponibileIrpefField As Double
        
        Private imponibileIrpefFieldSpecified As Boolean
        
        Private ritenuteIrpefField As Double
        
        Private ritenuteIrpefFieldSpecified As Boolean
        
        Private ritenutePrevidenzialiBenField As Double
        
        Private ritenutePrevidenzialiBenFieldSpecified As Boolean
        
        Private altreRitenuteField As Double
        
        Private altreRitenuteFieldSpecified As Boolean
        
        Private imponibilePrevidenzialeField As Double
        
        Private imponibilePrevidenzialeFieldSpecified As Boolean
        
        Private ritenutePrevidenzialiEnteField As Double
        
        Private ritenutePrevidenzialiEnteFieldSpecified As Boolean
        
        Private addizionaleComunaleField As Double
        
        Private addizionaleComunaleFieldSpecified As Boolean
        
        Private addizionaleRegionaleField As Double
        
        Private addizionaleRegionaleFieldSpecified As Boolean
        
        Private datoSensibileField As Boolean
        
        Private datoSensibileFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property CodiceBeneficiario() As String
            Get
                Return Me.codiceBeneficiarioField
            End Get
            Set
                Me.codiceBeneficiarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceSede() As String
            Get
                Return Me.codiceSedeField
            End Get
            Set
                Me.codiceSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceTipoPagamento() As String
            Get
                Return Me.codiceTipoPagamentoField
            End Get
            Set
                Me.codiceTipoPagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceContoCorrente() As String
            Get
                Return Me.codiceContoCorrenteField
            End Get
            Set
                Me.codiceContoCorrenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceSIOPE() As String
            Get
                Return Me.codiceSIOPEField
            End Get
            Set
                Me.codiceSIOPEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceSIOPEAggiuntivo() As String
            Get
                Return Me.codiceSIOPEAggiuntivoField
            End Get
            Set
                Me.codiceSIOPEAggiuntivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCUP() As String
            Get
                Return Me.codiceCUPField
            End Get
            Set
                Me.codiceCUPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCIG() As String
            Get
                Return Me.codiceCIGField
            End Get
            Set
                Me.codiceCIGField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsenzCommBonifico() As String
            Get
                Return Me.esenzCommBonificoField
            End Get
            Set
                Me.esenzCommBonificoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StampaAvviso() As String
            Get
                Return Me.stampaAvvisoField
            End Get
            Set
                Me.stampaAvvisoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bollo() As String
            Get
                Return Me.bolloField
            End Get
            Set
                Me.bolloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportoLordo() As Double
            Get
                Return Me.importoLordoField
            End Get
            Set
                Me.importoLordoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImportoLordoSpecified() As Boolean
            Get
                Return Me.importoLordoFieldSpecified
            End Get
            Set
                Me.importoLordoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImponibileIrpef() As Double
            Get
                Return Me.imponibileIrpefField
            End Get
            Set
                Me.imponibileIrpefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImponibileIrpefSpecified() As Boolean
            Get
                Return Me.imponibileIrpefFieldSpecified
            End Get
            Set
                Me.imponibileIrpefFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RitenuteIrpef() As Double
            Get
                Return Me.ritenuteIrpefField
            End Get
            Set
                Me.ritenuteIrpefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RitenuteIrpefSpecified() As Boolean
            Get
                Return Me.ritenuteIrpefFieldSpecified
            End Get
            Set
                Me.ritenuteIrpefFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RitenutePrevidenzialiBen() As Double
            Get
                Return Me.ritenutePrevidenzialiBenField
            End Get
            Set
                Me.ritenutePrevidenzialiBenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RitenutePrevidenzialiBenSpecified() As Boolean
            Get
                Return Me.ritenutePrevidenzialiBenFieldSpecified
            End Get
            Set
                Me.ritenutePrevidenzialiBenFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AltreRitenute() As Double
            Get
                Return Me.altreRitenuteField
            End Get
            Set
                Me.altreRitenuteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AltreRitenuteSpecified() As Boolean
            Get
                Return Me.altreRitenuteFieldSpecified
            End Get
            Set
                Me.altreRitenuteFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImponibilePrevidenziale() As Double
            Get
                Return Me.imponibilePrevidenzialeField
            End Get
            Set
                Me.imponibilePrevidenzialeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImponibilePrevidenzialeSpecified() As Boolean
            Get
                Return Me.imponibilePrevidenzialeFieldSpecified
            End Get
            Set
                Me.imponibilePrevidenzialeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RitenutePrevidenzialiEnte() As Double
            Get
                Return Me.ritenutePrevidenzialiEnteField
            End Get
            Set
                Me.ritenutePrevidenzialiEnteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RitenutePrevidenzialiEnteSpecified() As Boolean
            Get
                Return Me.ritenutePrevidenzialiEnteFieldSpecified
            End Get
            Set
                Me.ritenutePrevidenzialiEnteFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddizionaleComunale() As Double
            Get
                Return Me.addizionaleComunaleField
            End Get
            Set
                Me.addizionaleComunaleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AddizionaleComunaleSpecified() As Boolean
            Get
                Return Me.addizionaleComunaleFieldSpecified
            End Get
            Set
                Me.addizionaleComunaleFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddizionaleRegionale() As Double
            Get
                Return Me.addizionaleRegionaleField
            End Get
            Set
                Me.addizionaleRegionaleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AddizionaleRegionaleSpecified() As Boolean
            Get
                Return Me.addizionaleRegionaleFieldSpecified
            End Get
            Set
                Me.addizionaleRegionaleFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatoSensibile() As Boolean
            Get
                Return Me.datoSensibileField
            End Get
            Set
                Me.datoSensibileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DatoSensibileSpecified() As Boolean
            Get
                Return Me.datoSensibileFieldSpecified
            End Get
            Set
                Me.datoSensibileFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Allegato_Types
        
        Private codiceProgettoField As String
        
        Private causaleField As String
        
        Private importoField As Double
        
        Private codiceFiscaleBeneficiarioField As String
        
        '''<remarks/>
        Public Property CodiceProgetto() As String
            Get
                Return Me.codiceProgettoField
            End Get
            Set
                Me.codiceProgettoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Causale() As String
            Get
                Return Me.causaleField
            End Get
            Set
                Me.causaleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Importo() As Double
            Get
                Return Me.importoField
            End Get
            Set
                Me.importoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceFiscaleBeneficiario() As String
            Get
                Return Me.codiceFiscaleBeneficiarioField
            End Get
            Set
                Me.codiceFiscaleBeneficiarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateDelDocumento_Types
        
        Private tipoDocumentoField As CreateDelDocumento_TypesTipoDocumento
        
        Private dataMovimentoField As Date
        
        Private dataMovimentoFieldSpecified As Boolean
        
        Private oggettoField As String
        
        Private codiceCapitoloField As String
        
        Private numeroDocumentoPCField As String
        
        Private numeroDocumentoSostField As String
        
        Private importoField As Double
        
        Private importoFieldSpecified As Boolean
        
        Private importo_Plur1Field As Double
        
        Private importo_Plur1FieldSpecified As Boolean
        
        Private importo_Plur2Field As Double
        
        Private importo_Plur2FieldSpecified As Boolean
        
        Private tipoAttoField As String
        
        Private dataAttoField As Date
        
        Private dataAttoFieldSpecified As Boolean
        
        Private numeroAttoField As String
        
        Private strutturaField As String
        
        Private contoEconomicaField As String
        
        Private codiceFiscaleField As String
        
        Private valido770Field As String
        
        Private tipologiaRedditoField As String
        
        Private rateiField As Double
        
        Private rateiFieldSpecified As Boolean
        
        Private imponibileIrapField As Double
        
        Private imponibileIrapFieldSpecified As Boolean
        
        Private impostaIrapField As Double
        
        Private impostaIrapFieldSpecified As Boolean
        
        Private riscontiField As Double
        
        Private riscontiFieldSpecified As Boolean
        
        Private importoIVAField As Double
        
        Private importoIVAFieldSpecified As Boolean
        
        Private allegatoField As Allegato_Types
        
        Private cOGField As String
        
        Private cOG_Plur1Field As String
        
        Private cOG_Plur2Field As String
        
        Private collegatoAMandatoField As String
        
        Private beneficiariField() As Beneficiario_Types
        
        Private reversaliCollField() As ReversaleColl_Types
        
        Private pianoContiFinaField As String
        
        Private pianoContiFina_Plur1Field As String
        
        Private pianoContiFina_Plur2Field As String
        
        Private mandRevSostituitoField As Integer
        
        Private mandRevSostituitoFieldSpecified As Boolean
        
        Private codContoEvidenzaField As String
        
        Private preImpegnoAutomaticoField As String
        
        Private sistemazioneContabileField As String
        
        Private dataEsecuzionePagamentoField As Date
        
        Private dataEsecuzionePagamentoFieldSpecified As Boolean
        
        Private motivazioneField As String
        
        Private riaccertamentoField As String
        
        Private identificativoAttoField As String
        
        Private idUnivocoChiamataField As String
        
        Private idUnivocoSistemaChiamanteField As String
        
        Private campoDispN01Field As Double
        
        Private campoDispN01FieldSpecified As Boolean
        
        Private campoDispN02Field As Double
        
        Private campoDispN02FieldSpecified As Boolean
        
        Private campoDispV01Field As String
        
        Private campoDispV02Field As String
        
        Private campoDispD01Field As Date
        
        Private campoDispD01FieldSpecified As Boolean
        
        Private campoDispD02Field As Date
        
        Private campoDispD02FieldSpecified As Boolean
        
        '''<remarks/>
        Public Property TipoDocumento() As CreateDelDocumento_TypesTipoDocumento
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DataMovimento() As Date
            Get
                Return Me.dataMovimentoField
            End Get
            Set
                Me.dataMovimentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataMovimentoSpecified() As Boolean
            Get
                Return Me.dataMovimentoFieldSpecified
            End Get
            Set
                Me.dataMovimentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Oggetto() As String
            Get
                Return Me.oggettoField
            End Get
            Set
                Me.oggettoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumentoPC() As String
            Get
                Return Me.numeroDocumentoPCField
            End Get
            Set
                Me.numeroDocumentoPCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumentoSost() As String
            Get
                Return Me.numeroDocumentoSostField
            End Get
            Set
                Me.numeroDocumentoSostField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Importo() As Double
            Get
                Return Me.importoField
            End Get
            Set
                Me.importoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImportoSpecified() As Boolean
            Get
                Return Me.importoFieldSpecified
            End Get
            Set
                Me.importoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Importo_Plur1() As Double
            Get
                Return Me.importo_Plur1Field
            End Get
            Set
                Me.importo_Plur1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Importo_Plur1Specified() As Boolean
            Get
                Return Me.importo_Plur1FieldSpecified
            End Get
            Set
                Me.importo_Plur1FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Importo_Plur2() As Double
            Get
                Return Me.importo_Plur2Field
            End Get
            Set
                Me.importo_Plur2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Importo_Plur2Specified() As Boolean
            Get
                Return Me.importo_Plur2FieldSpecified
            End Get
            Set
                Me.importo_Plur2FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoAtto() As String
            Get
                Return Me.tipoAttoField
            End Get
            Set
                Me.tipoAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DataAtto() As Date
            Get
                Return Me.dataAttoField
            End Get
            Set
                Me.dataAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataAttoSpecified() As Boolean
            Get
                Return Me.dataAttoFieldSpecified
            End Get
            Set
                Me.dataAttoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroAtto() As String
            Get
                Return Me.numeroAttoField
            End Get
            Set
                Me.numeroAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Struttura() As String
            Get
                Return Me.strutturaField
            End Get
            Set
                Me.strutturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContoEconomica() As String
            Get
                Return Me.contoEconomicaField
            End Get
            Set
                Me.contoEconomicaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceFiscale() As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valido770() As String
            Get
                Return Me.valido770Field
            End Get
            Set
                Me.valido770Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipologiaReddito() As String
            Get
                Return Me.tipologiaRedditoField
            End Get
            Set
                Me.tipologiaRedditoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ratei() As Double
            Get
                Return Me.rateiField
            End Get
            Set
                Me.rateiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RateiSpecified() As Boolean
            Get
                Return Me.rateiFieldSpecified
            End Get
            Set
                Me.rateiFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImponibileIrap() As Double
            Get
                Return Me.imponibileIrapField
            End Get
            Set
                Me.imponibileIrapField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImponibileIrapSpecified() As Boolean
            Get
                Return Me.imponibileIrapFieldSpecified
            End Get
            Set
                Me.imponibileIrapFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImpostaIrap() As Double
            Get
                Return Me.impostaIrapField
            End Get
            Set
                Me.impostaIrapField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImpostaIrapSpecified() As Boolean
            Get
                Return Me.impostaIrapFieldSpecified
            End Get
            Set
                Me.impostaIrapFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Risconti() As Double
            Get
                Return Me.riscontiField
            End Get
            Set
                Me.riscontiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RiscontiSpecified() As Boolean
            Get
                Return Me.riscontiFieldSpecified
            End Get
            Set
                Me.riscontiFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportoIVA() As Double
            Get
                Return Me.importoIVAField
            End Get
            Set
                Me.importoIVAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImportoIVASpecified() As Boolean
            Get
                Return Me.importoIVAFieldSpecified
            End Get
            Set
                Me.importoIVAFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Allegato() As Allegato_Types
            Get
                Return Me.allegatoField
            End Get
            Set
                Me.allegatoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COG() As String
            Get
                Return Me.cOGField
            End Get
            Set
                Me.cOGField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COG_Plur1() As String
            Get
                Return Me.cOG_Plur1Field
            End Get
            Set
                Me.cOG_Plur1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COG_Plur2() As String
            Get
                Return Me.cOG_Plur2Field
            End Get
            Set
                Me.cOG_Plur2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CollegatoAMandato() As String
            Get
                Return Me.collegatoAMandatoField
            End Get
            Set
                Me.collegatoAMandatoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Beneficiario", IsNullable:=false)>  _
        Public Property Beneficiari() As Beneficiario_Types()
            Get
                Return Me.beneficiariField
            End Get
            Set
                Me.beneficiariField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ReversaleColl", IsNullable:=false)>  _
        Public Property ReversaliColl() As ReversaleColl_Types()
            Get
                Return Me.reversaliCollField
            End Get
            Set
                Me.reversaliCollField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PianoContiFina() As String
            Get
                Return Me.pianoContiFinaField
            End Get
            Set
                Me.pianoContiFinaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PianoContiFina_Plur1() As String
            Get
                Return Me.pianoContiFina_Plur1Field
            End Get
            Set
                Me.pianoContiFina_Plur1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PianoContiFina_Plur2() As String
            Get
                Return Me.pianoContiFina_Plur2Field
            End Get
            Set
                Me.pianoContiFina_Plur2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MandRevSostituito() As Integer
            Get
                Return Me.mandRevSostituitoField
            End Get
            Set
                Me.mandRevSostituitoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MandRevSostituitoSpecified() As Boolean
            Get
                Return Me.mandRevSostituitoFieldSpecified
            End Get
            Set
                Me.mandRevSostituitoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodContoEvidenza() As String
            Get
                Return Me.codContoEvidenzaField
            End Get
            Set
                Me.codContoEvidenzaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PreImpegnoAutomatico() As String
            Get
                Return Me.preImpegnoAutomaticoField
            End Get
            Set
                Me.preImpegnoAutomaticoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SistemazioneContabile() As String
            Get
                Return Me.sistemazioneContabileField
            End Get
            Set
                Me.sistemazioneContabileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DataEsecuzionePagamento() As Date
            Get
                Return Me.dataEsecuzionePagamentoField
            End Get
            Set
                Me.dataEsecuzionePagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataEsecuzionePagamentoSpecified() As Boolean
            Get
                Return Me.dataEsecuzionePagamentoFieldSpecified
            End Get
            Set
                Me.dataEsecuzionePagamentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Motivazione() As String
            Get
                Return Me.motivazioneField
            End Get
            Set
                Me.motivazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Riaccertamento() As String
            Get
                Return Me.riaccertamentoField
            End Get
            Set
                Me.riaccertamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificativoAtto() As String
            Get
                Return Me.identificativoAttoField
            End Get
            Set
                Me.identificativoAttoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdUnivocoChiamata() As String
            Get
                Return Me.idUnivocoChiamataField
            End Get
            Set
                Me.idUnivocoChiamataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdUnivocoSistemaChiamante() As String
            Get
                Return Me.idUnivocoSistemaChiamanteField
            End Get
            Set
                Me.idUnivocoSistemaChiamanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CampoDispN01() As Double
            Get
                Return Me.campoDispN01Field
            End Get
            Set
                Me.campoDispN01Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CampoDispN01Specified() As Boolean
            Get
                Return Me.campoDispN01FieldSpecified
            End Get
            Set
                Me.campoDispN01FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CampoDispN02() As Double
            Get
                Return Me.campoDispN02Field
            End Get
            Set
                Me.campoDispN02Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CampoDispN02Specified() As Boolean
            Get
                Return Me.campoDispN02FieldSpecified
            End Get
            Set
                Me.campoDispN02FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CampoDispV01() As String
            Get
                Return Me.campoDispV01Field
            End Get
            Set
                Me.campoDispV01Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CampoDispV02() As String
            Get
                Return Me.campoDispV02Field
            End Get
            Set
                Me.campoDispV02Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property CampoDispD01() As Date
            Get
                Return Me.campoDispD01Field
            End Get
            Set
                Me.campoDispD01Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CampoDispD01Specified() As Boolean
            Get
                Return Me.campoDispD01FieldSpecified
            End Get
            Set
                Me.campoDispD01FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property CampoDispD02() As Date
            Get
                Return Me.campoDispD02Field
            End Get
            Set
                Me.campoDispD02Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CampoDispD02Specified() As Boolean
            Get
                Return Me.campoDispD02FieldSpecified
            End Get
            Set
                Me.campoDispD02FieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum CreateDelDocumento_TypesTipoDocumento
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("PRE-IMP")>  _
        PREIMP
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("IMP-DEF")>  _
        IMPDEF
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("IMP-PER")>  _
        IMPPER
        
        '''<remarks/>
        LIQ
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-ECO")>  _
        DELECO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-LIQ")>  _
        DELLIQ
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-IMP")>  _
        DELIMP
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-PREIMP")>  _
        DELPREIMP
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-PREIMP")>  _
        VARPREIMP
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-IMP")>  _
        VARIMP
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-IMPDEF")>  _
        VARIMPDEF
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-IMPPER")>  _
        VARIMPPER
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-LIQ")>  _
        VARLIQ
        
        '''<remarks/>
        MAND
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("ST-MAND")>  _
        STMAND
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-MAND")>  _
        VARMAND
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-MAND")>  _
        DELMAND
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("SOST-MAND")>  _
        SOSTMAND
        
        '''<remarks/>
        ACC
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-ACC")>  _
        DELACC
        
        '''<remarks/>
        REV
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("ST-REV")>  _
        STREV
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-REV")>  _
        VARREV
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-REV")>  _
        DELREV
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("REV-COLL")>  _
        REVCOLL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-REV-COLL")>  _
        VARREVCOLL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-REV-COLL")>  _
        DELREVCOLL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("SOST-REV-COLL")>  _
        SOSTREVCOLL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("ACC-COLL")>  _
        ACCCOLL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VAR-ACC-COLL")>  _
        VARACCCOLL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("DEL-ACC-COLL")>  _
        DELACCCOLL
        
        '''<remarks/>
        INSUS
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("PREIMP-DELIBERA")>  _
        PREIMPDELIBERA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("IMP-PROVV")>  _
        IMPPROVV
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PrenotazionePreimpegni_Types
        
        Private tipoOperazioneField As String
        
        Private numeroPreimpegnoField As String
        
        Private importoField As Double
        
        '''<remarks/>
        Public Property TipoOperazione() As String
            Get
                Return Me.tipoOperazioneField
            End Get
            Set
                Me.tipoOperazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroPreimpegno() As String
            Get
                Return Me.numeroPreimpegnoField
            End Get
            Set
                Me.numeroPreimpegnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Importo() As Double
            Get
                Return Me.importoField
            End Get
            Set
                Me.importoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneImpegniPerenti_Types
        
        Private annoFinanziarioField As String
        
        Private codiceCapitoloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoFinanziario() As String
            Get
                Return Me.annoFinanziarioField
            End Get
            Set
                Me.annoFinanziarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazionePreimpegniAperti_Types
        
        Private annoFinanziarioField As String
        
        Private codiceCapitoloField As String
        
        Private strutturaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoFinanziario() As String
            Get
                Return Me.annoFinanziarioField
            End Get
            Set
                Me.annoFinanziarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Struttura() As String
            Get
                Return Me.strutturaField
            End Get
            Set
                Me.strutturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneLiquidazioniAperte_Types
        
        Private annoFinanziarioField As String
        
        Private codiceCapitoloField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoFinanziario() As String
            Get
                Return Me.annoFinanziarioField
            End Get
            Set
                Me.annoFinanziarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneImpegniAperti_Types
        
        Private annoFinanziarioField As String
        
        Private codiceCapitoloField As String
        
        Private strutturaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoFinanziario() As String
            Get
                Return Me.annoFinanziarioField
            End Get
            Set
                Me.annoFinanziarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Struttura() As String
            Get
                Return Me.strutturaField
            End Get
            Set
                Me.strutturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DisponibilitaPreImpegno_Types
        
        Private numeroPreimpegnoField As String
        
        Private strutturaField As String
        
        '''<remarks/>
        Public Property NumeroPreimpegno() As String
            Get
                Return Me.numeroPreimpegnoField
            End Get
            Set
                Me.numeroPreimpegnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Struttura() As String
            Get
                Return Me.strutturaField
            End Get
            Set
                Me.strutturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneObiettiviGestionali_Types
        
        Private annoField As String
        
        Private codiceCapitoloField As String
        
        Private ufficioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property Anno() As String
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ufficio() As String
            Get
                Return Me.ufficioField
            End Get
            Set
                Me.ufficioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneBilancio_Types
        
        Private annoBilancioField As String
        
        Private codiceCapitoloField As String
        
        Private strutturaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoBilancio() As String
            Get
                Return Me.annoBilancioField
            End Get
            Set
                Me.annoBilancioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceCapitolo() As String
            Get
                Return Me.codiceCapitoloField
            End Get
            Set
                Me.codiceCapitoloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Struttura() As String
            Get
                Return Me.strutturaField
            End Get
            Set
                Me.strutturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InterrogazioneCapitoli_Types
        
        Private annoBilancioField As String
        
        Private strutturaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")>  _
        Public Property AnnoBilancio() As String
            Get
                Return Me.annoBilancioField
            End Get
            Set
                Me.annoBilancioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Struttura() As String
            Get
                Return Me.strutturaField
            End Get
            Set
                Me.strutturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Richiesta_Types
        
        Private itemField As Object
        
        Private itemElementNameField As ItemChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CreateDelDocumento", GetType(CreateDelDocumento_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("DisponibilitaImpegno", GetType(DisponibilitaImpegno_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("DisponibilitaPreImpegno", GetType(DisponibilitaPreImpegno_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogaBeneficiariLiq", GetType(InterrogaBeneficiariLiq_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogaCapitoloEntrate", GetType(InterrogaCapitoloEntrata_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogaCodiceSiope", GetType(InterrogaCodiceSiope_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogaMandatiBeneficiariAtto", GetType(InterrogaMandatiBeneficiariAtto_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogaReversaliCollegabili", GetType(InterrogaReversaliCollegabili_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneBilancio", GetType(InterrogazioneBilancio_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneCapitoli", GetType(InterrogazioneCapitoli_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneCapitoliLiquidazioni", GetType(InterrogazioneCapitoli_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneContratti", GetType(InterrogazioneContratti_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneImpegniAperti", GetType(InterrogazioneImpegniAperti_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneImpegniPerenti", GetType(InterrogazioneImpegniPerenti_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneLiquidazioniAperte", GetType(InterrogazioneLiquidazioniAperte_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneListaContratti", GetType(InterrogazioneListaContratti_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneMandatiTrasparenza", GetType(InterrogazioneMandatiTrasparenza_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneObiettiviGestionali", GetType(InterrogazioneObiettiviGestionali_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazionePCF", GetType(InterrogazionePCF_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazionePreimpegniAperti", GetType(InterrogazionePreimpegniAperti_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("InterrogazioneTipologiaReddito", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("PrenotazionePreimpegni", GetType(PrenotazionePreimpegni_Types)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        CreateDelDocumento
        
        '''<remarks/>
        DisponibilitaImpegno
        
        '''<remarks/>
        DisponibilitaPreImpegno
        
        '''<remarks/>
        InterrogaBeneficiariLiq
        
        '''<remarks/>
        InterrogaCapitoloEntrate
        
        '''<remarks/>
        InterrogaCodiceSiope
        
        '''<remarks/>
        InterrogaMandatiBeneficiariAtto
        
        '''<remarks/>
        InterrogaReversaliCollegabili
        
        '''<remarks/>
        InterrogazioneBilancio
        
        '''<remarks/>
        InterrogazioneCapitoli
        
        '''<remarks/>
        InterrogazioneCapitoliLiquidazioni
        
        '''<remarks/>
        InterrogazioneContratti
        
        '''<remarks/>
        InterrogazioneImpegniAperti
        
        '''<remarks/>
        InterrogazioneImpegniPerenti
        
        '''<remarks/>
        InterrogazioneLiquidazioniAperte
        
        '''<remarks/>
        InterrogazioneListaContratti
        
        '''<remarks/>
        InterrogazioneMandatiTrasparenza
        
        '''<remarks/>
        InterrogazioneObiettiviGestionali
        
        '''<remarks/>
        InterrogazionePCF
        
        '''<remarks/>
        InterrogazionePreimpegniAperti
        
        '''<remarks/>
        InterrogazioneTipologiaReddito
        
        '''<remarks/>
        PrenotazionePreimpegni
    End Enum
End Namespace
