'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.3625
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'
Namespace Intema.WS.Ana.Risposta
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlRootAttribute("Messaggio_Risposta", [Namespace]:="", IsNullable:=false)>  _
    Partial Public Class MessaggioRisposta_Types
        
        Private intestazioneField As Intestazione_Types
        
        Private itemField As Object
        
        '''<remarks/>
        Public Property Intestazione() As Intestazione_Types
            Get
                Return Me.intestazioneField
            End Get
            Set
                Me.intestazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Eccezione", GetType(Eccezione_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Successo", GetType(Successo_Types))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Intestazione_Types
        
        Private infoMittDestField As String
        
        Private applicazioneField As String
        
        '''<remarks/>
        Public Property InfoMittDest() As String
            Get
                Return Me.infoMittDestField
            End Get
            Set
                Me.infoMittDestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applicazione() As String
            Get
                Return Me.applicazioneField
            End Get
            Set
                Me.applicazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Eccezione_Types
        
        Private codiceField As String
        
        Private descrizioneField As String
        
        Private exceptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property Codice() As String
            Get
                Return Me.codiceField
            End Get
            Set
                Me.codiceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Exception() As String
            Get
                Return Me.exceptionField
            End Get
            Set
                Me.exceptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_ModificaContoBancario_Types
        
        Private idAnagraficaField As String
        
        Private idSedeField As String
        
        Private idContoCorrenteField As String
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set
                Me.idSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdContoCorrente() As String
            Get
                Return Me.idContoCorrenteField
            End Get
            Set
                Me.idContoCorrenteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_ModificaSede_Types
        
        Private idAnagraficaField As String
        
        Private idSedeField As String
        
        Private idTipoPagamentoField As String
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set
                Me.idSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTipoPagamento() As String
            Get
                Return Me.idTipoPagamentoField
            End Get
            Set
                Me.idTipoPagamentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_ModificaAnagrafica_Types
        
        Private idAnagraficaField As String
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_InterrogaComuni_Types
        
        Private comuneField() As Comune_Types
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Comune")>  _
        Public Property Comune() As Comune_Types()
            Get
                Return Me.comuneField
            End Get
            Set
                Me.comuneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Comune_Types
        
        Private idComuneField As String
        
        Private descrizioneField As String
        
        Private codiceIstatField As String
        
        Private cAPField As String
        
        Private codiceBelFioreField As String
        
        Private codProvinciaField As String
        
        Private provinciaField As String
        
        Private codRegioneField As String
        
        Private regioneField As String
        
        Private codRipartizioneGeograficaField As String
        
        Private descRipartizioneGeograficaField As String
        
        Private nazioneField As String
        
        '''<remarks/>
        Public Property IdComune() As String
            Get
                Return Me.idComuneField
            End Get
            Set
                Me.idComuneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodiceIstat() As String
            Get
                Return Me.codiceIstatField
            End Get
            Set
                Me.codiceIstatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CAP() As String
            Get
                Return Me.cAPField
            End Get
            Set
                Me.cAPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodiceBelFiore() As String
            Get
                Return Me.codiceBelFioreField
            End Get
            Set
                Me.codiceBelFioreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodProvincia() As String
            Get
                Return Me.codProvinciaField
            End Get
            Set
                Me.codProvinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodRegione() As String
            Get
                Return Me.codRegioneField
            End Get
            Set
                Me.codRegioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Regione() As String
            Get
                Return Me.regioneField
            End Get
            Set
                Me.regioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodRipartizioneGeografica() As String
            Get
                Return Me.codRipartizioneGeograficaField
            End Get
            Set
                Me.codRipartizioneGeograficaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DescRipartizioneGeografica() As String
            Get
                Return Me.descRipartizioneGeograficaField
            End Get
            Set
                Me.descRipartizioneGeograficaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Nazione() As String
            Get
                Return Me.nazioneField
            End Get
            Set
                Me.nazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_CreaContoBancario_Types
        
        Private idAnagraficaField As String
        
        Private idSedeField As String
        
        Private idTipoPagamentoField As String
        
        Private idContoCorrenteField As String
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set
                Me.idSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTipoPagamento() As String
            Get
                Return Me.idTipoPagamentoField
            End Get
            Set
                Me.idTipoPagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdContoCorrente() As String
            Get
                Return Me.idContoCorrenteField
            End Get
            Set
                Me.idContoCorrenteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_CreaSede_Types
        
        Private idAnagraficaField As String
        
        Private idSedeField As String
        
        Private idTipoPagamentoField As String
        
        Private idContoCorrenteField As String
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set
                Me.idSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTipoPagamento() As String
            Get
                Return Me.idTipoPagamentoField
            End Get
            Set
                Me.idTipoPagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdContoCorrente() As String
            Get
                Return Me.idContoCorrenteField
            End Get
            Set
                Me.idContoCorrenteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_CreaAnagrafica_Types
        
        Private idAnagraficaField As String
        
        Private idSedeField As String
        
        Private idTipoPagamentoField As String
        
        Private idContoCorrenteField As String
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set
                Me.idSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTipoPagamento() As String
            Get
                Return Me.idTipoPagamentoField
            End Get
            Set
                Me.idTipoPagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdContoCorrente() As String
            Get
                Return Me.idContoCorrenteField
            End Get
            Set
                Me.idContoCorrenteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_VerificaAnagrafica_Types
        
        Private anagraficaField As Anagrafica_Types
        
        '''<remarks/>
        Public Property Anagrafica() As Anagrafica_Types
            Get
                Return Me.anagraficaField
            End Get
            Set
                Me.anagraficaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Anagrafica_Types
        
        Private idAnagraficaField As String
        
        Private tipoAnagraficaField As System.Nullable(Of Anagrafica_TypesTipoAnagrafica)
        
        Private partitaIvaField As String
        
        Private denominazioneField As String
        
        Private cognomeLRField As String
        
        Private nomeLRField As String
        
        Private sessoLRField As System.Nullable(Of Anagrafica_TypesSessoLR)
        
        Private idComuneNSLRField As String
        
        Private comuneNSLRField As String
        
        Private dataNascitaLRField As System.Nullable(Of Date)
        
        Private indirizzoLRField As String
        
        Private idComuneRESLRField As String
        
        Private comuneRESLRField As String
        
        Private cAPRESLRField As String
        
        Private codiceFiscaleLRField As String
        
        Private codiceFiscaleField As String
        
        Private cognomeField As String
        
        Private nomeField As String
        
        Private altriNomiField As String
        
        Private sessoField As System.Nullable(Of Anagrafica_TypesSesso)
        
        Private idComuneNSField As String
        
        Private comuneNSField As String
        
        Private dataNascitaField As System.Nullable(Of Date)
        
        Private pignoramentoField As System.Nullable(Of Anagrafica_TypesPignoramento)
        
        Private notaPignoramentoField As String
        
        Private esteroField As System.Nullable(Of Anagrafica_TypesEstero)
        
        Private commissioniField As System.Nullable(Of Anagrafica_TypesCommissioni)
        
        Private listaSediField() As Sede_Types
        
        '''<remarks/>
        Public Property IdAnagrafica() As String
            Get
                Return Me.idAnagraficaField
            End Get
            Set
                Me.idAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TipoAnagrafica() As System.Nullable(Of Anagrafica_TypesTipoAnagrafica)
            Get
                Return Me.tipoAnagraficaField
            End Get
            Set
                Me.tipoAnagraficaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PartitaIva() As String
            Get
                Return Me.partitaIvaField
            End Get
            Set
                Me.partitaIvaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Denominazione() As String
            Get
                Return Me.denominazioneField
            End Get
            Set
                Me.denominazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CognomeLR() As String
            Get
                Return Me.cognomeLRField
            End Get
            Set
                Me.cognomeLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NomeLR() As String
            Get
                Return Me.nomeLRField
            End Get
            Set
                Me.nomeLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SessoLR() As System.Nullable(Of Anagrafica_TypesSessoLR)
            Get
                Return Me.sessoLRField
            End Get
            Set
                Me.sessoLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdComuneNSLR() As String
            Get
                Return Me.idComuneNSLRField
            End Get
            Set
                Me.idComuneNSLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ComuneNSLR() As String
            Get
                Return Me.comuneNSLRField
            End Get
            Set
                Me.comuneNSLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property DataNascitaLR() As System.Nullable(Of Date)
            Get
                Return Me.dataNascitaLRField
            End Get
            Set
                Me.dataNascitaLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IndirizzoLR() As String
            Get
                Return Me.indirizzoLRField
            End Get
            Set
                Me.indirizzoLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdComuneRESLR() As String
            Get
                Return Me.idComuneRESLRField
            End Get
            Set
                Me.idComuneRESLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ComuneRESLR() As String
            Get
                Return Me.comuneRESLRField
            End Get
            Set
                Me.comuneRESLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CAPRESLR() As String
            Get
                Return Me.cAPRESLRField
            End Get
            Set
                Me.cAPRESLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodiceFiscaleLR() As String
            Get
                Return Me.codiceFiscaleLRField
            End Get
            Set
                Me.codiceFiscaleLRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodiceFiscale() As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Cognome() As String
            Get
                Return Me.cognomeField
            End Get
            Set
                Me.cognomeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AltriNomi() As String
            Get
                Return Me.altriNomiField
            End Get
            Set
                Me.altriNomiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Sesso() As System.Nullable(Of Anagrafica_TypesSesso)
            Get
                Return Me.sessoField
            End Get
            Set
                Me.sessoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdComuneNS() As String
            Get
                Return Me.idComuneNSField
            End Get
            Set
                Me.idComuneNSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ComuneNS() As String
            Get
                Return Me.comuneNSField
            End Get
            Set
                Me.comuneNSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property DataNascita() As System.Nullable(Of Date)
            Get
                Return Me.dataNascitaField
            End Get
            Set
                Me.dataNascitaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Pignoramento() As System.Nullable(Of Anagrafica_TypesPignoramento)
            Get
                Return Me.pignoramentoField
            End Get
            Set
                Me.pignoramentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NotaPignoramento() As String
            Get
                Return Me.notaPignoramentoField
            End Get
            Set
                Me.notaPignoramentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Estero() As System.Nullable(Of Anagrafica_TypesEstero)
            Get
                Return Me.esteroField
            End Get
            Set
                Me.esteroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Commissioni() As System.Nullable(Of Anagrafica_TypesCommissioni)
            Get
                Return Me.commissioniField
            End Get
            Set
                Me.commissioniField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Sede", IsNullable:=false)>  _
        Public Property ListaSedi() As Sede_Types()
            Get
                Return Me.listaSediField
            End Get
            Set
                Me.listaSediField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Anagrafica_TypesTipoAnagrafica
        
        '''<remarks/>
        F
        
        '''<remarks/>
        G
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Anagrafica_TypesSessoLR
        
        '''<remarks/>
        F
        
        '''<remarks/>
        M
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Anagrafica_TypesSesso
        
        '''<remarks/>
        F
        
        '''<remarks/>
        M
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Anagrafica_TypesPignoramento
        
        '''<remarks/>
        S
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Anagrafica_TypesEstero
        
        '''<remarks/>
        S
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Anagrafica_TypesCommissioni
        
        '''<remarks/>
        S
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Sede_Types
        
        Private idSedeField As String
        
        Private indirizzoField As String
        
        Private idComuneField As String
        
        Private comuneField As String
        
        Private cAPField As String
        
        Private telefonoField As String
        
        Private eMailField As String
        
        Private faxField As String
        
        Private bolloField As System.Nullable(Of Sede_TypesBollo)
        
        Private dataCreazioneField As System.Nullable(Of Date)
        
        Private nomeSedeField As String
        
        Private idTipoPagamentoField As String
        
        Private descTipoPagamentoField As String
        
        Private listaDatiBancariField() As DatiBancari_Types
        
        '''<remarks/>
        Public Property IdSede() As String
            Get
                Return Me.idSedeField
            End Get
            Set
                Me.idSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set
                Me.indirizzoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdComune() As String
            Get
                Return Me.idComuneField
            End Get
            Set
                Me.idComuneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Comune() As String
            Get
                Return Me.comuneField
            End Get
            Set
                Me.comuneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CAP() As String
            Get
                Return Me.cAPField
            End Get
            Set
                Me.cAPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property EMail() As String
            Get
                Return Me.eMailField
            End Get
            Set
                Me.eMailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Bollo() As System.Nullable(Of Sede_TypesBollo)
            Get
                Return Me.bolloField
            End Get
            Set
                Me.bolloField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property DataCreazione() As System.Nullable(Of Date)
            Get
                Return Me.dataCreazioneField
            End Get
            Set
                Me.dataCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NomeSede() As String
            Get
                Return Me.nomeSedeField
            End Get
            Set
                Me.nomeSedeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdTipoPagamento() As String
            Get
                Return Me.idTipoPagamentoField
            End Get
            Set
                Me.idTipoPagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DescTipoPagamento() As String
            Get
                Return Me.descTipoPagamentoField
            End Get
            Set
                Me.descTipoPagamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ContoBancario", IsNullable:=false)>  _
        Public Property ListaDatiBancari() As DatiBancari_Types()
            Get
                Return Me.listaDatiBancariField
            End Get
            Set
                Me.listaDatiBancariField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum Sede_TypesBollo
        
        '''<remarks/>
        S
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DatiBancari_Types
        
        Private idContoCorrenteField As String
        
        Private nomeBancaField As String
        
        Private idAgenziaField As String
        
        Private contoCorrenteField As String
        
        Private modalitaPrincipaleField As System.Nullable(Of DatiBancari_TypesModalitaPrincipale)
        
        Private sedeAgenziaField As String
        
        Private indirizzoField As String
        
        Private cittaField As String
        
        Private aBIField As String
        
        Private cABField As String
        
        Private cINField As String
        
        Private iBANField As String
        
        '''<remarks/>
        Public Property IdContoCorrente() As String
            Get
                Return Me.idContoCorrenteField
            End Get
            Set
                Me.idContoCorrenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NomeBanca() As String
            Get
                Return Me.nomeBancaField
            End Get
            Set
                Me.nomeBancaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdAgenzia() As String
            Get
                Return Me.idAgenziaField
            End Get
            Set
                Me.idAgenziaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ContoCorrente() As String
            Get
                Return Me.contoCorrenteField
            End Get
            Set
                Me.contoCorrenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ModalitaPrincipale() As System.Nullable(Of DatiBancari_TypesModalitaPrincipale)
            Get
                Return Me.modalitaPrincipaleField
            End Get
            Set
                Me.modalitaPrincipaleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SedeAgenzia() As String
            Get
                Return Me.sedeAgenziaField
            End Get
            Set
                Me.sedeAgenziaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set
                Me.indirizzoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Citta() As String
            Get
                Return Me.cittaField
            End Get
            Set
                Me.cittaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ABI() As String
            Get
                Return Me.aBIField
            End Get
            Set
                Me.aBIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CAB() As String
            Get
                Return Me.cABField
            End Get
            Set
                Me.cABField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CIN() As String
            Get
                Return Me.cINField
            End Get
            Set
                Me.cINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IBAN() As String
            Get
                Return Me.iBANField
            End Get
            Set
                Me.iBANField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum DatiBancari_TypesModalitaPrincipale
        
        '''<remarks/>
        S
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Risposta_InterrogaAnagrafica_Types
        
        Private anagraficaField() As Anagrafica_Types
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Anagrafica")>  _
        Public Property Anagrafica() As Anagrafica_Types()
            Get
                Return Me.anagraficaField
            End Get
            Set
                Me.anagraficaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Successo_Types
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Risposta_CreaAnagrafica", GetType(Risposta_CreaAnagrafica_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_CreaContoBancario", GetType(Risposta_CreaContoBancario_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_CreaSede", GetType(Risposta_CreaSede_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_InterrogaAnagrafica", GetType(Risposta_InterrogaAnagrafica_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_InterrogaComuni", GetType(Risposta_InterrogaComuni_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_ModificaAnagrafica", GetType(Risposta_ModificaAnagrafica_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_ModificaContoBancario", GetType(Risposta_ModificaContoBancario_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_ModificaSede", GetType(Risposta_ModificaSede_Types)),  _
         System.Xml.Serialization.XmlElementAttribute("Risposta_VerificaAnagrafica", GetType(Risposta_VerificaAnagrafica_Types))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
End Namespace
