'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.1433
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="SICInterfaceSOAP11Binding", [Namespace]:="http://ws.latraccia.it")>  _
Partial Public Class SICInterface
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private querySICOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New(ByVal stringUrl As String)
        MyBase.New()
        Me.Timeout = System.Threading.Timeout.Infinite
        Me.Url = stringUrl
    End Sub
    
    '''<remarks/>
    Public Event querySICCompleted As querySICCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:querySIC", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
    Public Function querySIC(<System.Xml.Serialization.XmlElementAttribute("querySIC", [Namespace]:="http://ws.latraccia.it/xsd")> ByVal querySIC1 As querySIC) As <System.Xml.Serialization.XmlElementAttribute("querySICResponse", [Namespace]:="http://ws.latraccia.it/xsd")> querySICResponse
        Dim results() As Object = Me.Invoke("querySIC", New Object() {querySIC1})
        Return CType(results(0),querySICResponse)
    End Function
    
    '''<remarks/>
    Public Function BeginquerySIC(ByVal querySIC1 As querySIC, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("querySIC", New Object() {querySIC1}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndquerySIC(ByVal asyncResult As System.IAsyncResult) As querySICResponse
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),querySICResponse)
    End Function
    
    '''<remarks/>
    Public Overloads Sub querySICAsync(ByVal querySIC1 As querySIC)
        Me.querySICAsync(querySIC1, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub querySICAsync(ByVal querySIC1 As querySIC, ByVal userState As Object)
        If (Me.querySICOperationCompleted Is Nothing) Then
            Me.querySICOperationCompleted = AddressOf Me.OnquerySICOperationCompleted
        End If
        Me.InvokeAsync("querySIC", New Object() {querySIC1}, Me.querySICOperationCompleted, userState)
    End Sub
    
    Private Sub OnquerySICOperationCompleted(ByVal arg As Object)
        If (Not (Me.querySICCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent querySICCompleted(Me, New querySICCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ws.latraccia.it/xsd")>  _
Partial Public Class querySIC
    
    Private qField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property q() As String
        Get
            Return Me.qField
        End Get
        Set
            Me.qField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ws.latraccia.it/xsd")>  _
Partial Public Class querySICResponse
    
    Private returnField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property [return]() As String
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")>  _
Public Delegate Sub querySICCompletedEventHandler(ByVal sender As Object, ByVal e As querySICCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class querySICCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As querySICResponse
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),querySICResponse)
        End Get
    End Property
End Class
